In [1]:
import numpy as np
import scipy 
import scipy.sparse as sp
from scipy.linalg import toeplitz
from sympy import *
from scipy import integrate
import math
from matplotlib import pyplot as plt
from scipy import signal, interpolate
import scipy.linalg as linalg
import scipy.sparse as sp
import scipy.sparse.linalg as spla
%pylab inline --no-import-all

ModuleNotFoundError: No module named 'sympy'

In [4]:
import numpy as np
import scipy 
import scipy.sparse as sp
from scipy.linalg import toeplitz
from scipy import integrate
import math
from scipy import signal, interpolate
import scipy.linalg as linalg
import scipy.sparse as sp
import scipy.sparse.linalg as spla

In [5]:
n=4
K_n  =toeplitz([2, -1]+[0]*(n-2))
T_n = toeplitz([2, -1]+[0]*(n-2))
T_n[0,0]=1
B_n = toeplitz([2, -1]+[0]*(n-2))
B_n[0,0]=1
B_n[n-1,n-1,]=1
C_n = toeplitz([2, -1]+[0]*(n-2))
C_n[0,n-1]=1
C_n[n-1,0,]=1

## 問題1-5-1
例１の２×２行列$K_2$は、$Λ$中の数値１と３を固有値としてもつ。この行列の単位ベクトル$q_1$と$q_2$はQの列ベクトルである。$QΛQ^T$を計算して$K_2$を復元せよ

In [ ]:
#1.5-1

n=2
K_n  =toeplitz([2, -1]+[0]*(n-2))
l,Q = np.linalg.eig(K_n)
L = np.eye(2)*l
Qt = np.transpose(Q)
K2 = (np.dot(np.dot(Q,L),Qt))

print('K='+ str(K_n) )
print ('L='+ str(L))
print('Q='+ str(Q))
print('Qt='+ str(Qt))
print('K2='+ str(K2))

## 問題1-5-2

固有ベクトル$y = (sinπh,sin2πh,,,,)$にKをかけると、その第１行は$sinπh$の定数倍となる。$sin2πh$に対して２倍角の公式を適用することにより、  
その定数$λ$を求めよ

### 解答
$2sinπh - 1sin2πh = λsinπh$  
$2sinπh - 2sinπhcosπh = λsinπh$  
$2(1 - cosπh)sinπh = λsinπh$  
$λ = 2 - 2cosπh$  

## 問題1-5-3
MATLABで$K=K_5$を生成し、その固有値を求めよ。  
結果は$(2-\sqrt{3},2-1,2-0,2+1,2+\sqrt{3})$となるはずである。  
$eが2*ones(5,1)-2cos([1:5]*pi/6)'$と一致することを示せ。



In [5]:
#1.5-3
#行列Kに関する固有値の問題

K5= toeplitz([2,-1,0,0,0], [0,-1,0,0,0])
l,Q = np.linalg.eig(K5)
a  = (np.ones((1,5)))
b = np.array([1,2,3,4,5])
c  = np.cos((np.pi/6)*b)
e = 2*a - 2*c
print(l)
print(e)

[ 3.73205081  3.          2.          0.26794919  1.        ]
[[ 0.26794919  1.          2.          3.          3.73205081]]


## 問題1-5-4

3の続きで[Q,E] = eig(K)により固有ベクトル行列Qを求めよ。離散正弦変換をDST = Q*diaf([-1 -1 1 -1 1])と定義するとその各列は性の要素から始まる。  
一方、行列JK = [1:5]'＊[1:5]はjかけるkを要素にもつ.DSTがsin(JK＊pi/6)/sqrt(3)と一致することを確認せよ

$K$での固有関数は$y(x)=sinkπx$  
$Q_{i,j} = sin\frac{k}{n+1}π$

In [6]:
#1/5-4
l,Q = np.linalg.eig(K5)
d = np.diag([1,1,1,1,-1])
DST = np.dot(Q,d)
DSTt = np.transpose(DST)
print(DST)
a = np.dot(np.diag([1,2,3,4,5]),np.ones((5,1)))
b = np.array([1,2,3,4,5])
JK=a*b
DST2 = np.sin(JK*(np.pi/6))/np.sqrt(3)
print(DST2)
print(np.dot(DST,DST.T))
print(np.dot(DST2,DST2.T))


[[  2.88675135e-01   5.00000000e-01   5.77350269e-01   2.88675135e-01
    5.00000000e-01]
 [ -5.00000000e-01  -5.00000000e-01  -1.22011980e-16   5.00000000e-01
    5.00000000e-01]
 [  5.77350269e-01   6.39000977e-16  -5.77350269e-01   5.77350269e-01
    3.68521763e-16]
 [ -5.00000000e-01   5.00000000e-01   2.09033864e-16   5.00000000e-01
   -5.00000000e-01]
 [  2.88675135e-01  -5.00000000e-01   5.77350269e-01   2.88675135e-01
   -5.00000000e-01]]
[[  2.88675135e-01   5.00000000e-01   5.77350269e-01   5.00000000e-01
    2.88675135e-01]
 [  5.00000000e-01   5.00000000e-01   7.07050159e-17  -5.00000000e-01
   -5.00000000e-01]
 [  5.77350269e-01   7.07050159e-17  -5.77350269e-01  -1.41410032e-16
    5.77350269e-01]
 [  5.00000000e-01  -5.00000000e-01  -1.41410032e-16   5.00000000e-01
   -5.00000000e-01]
 [  2.88675135e-01  -5.00000000e-01   5.77350269e-01  -5.00000000e-01
    2.88675135e-01]]
[[  1.00000000e+00   2.77555756e-16   2.95283184e-16   1.94289029e-16
    3.33066907e-16]
 [  2.77

## 問題1-5-5
$B = B_6$として[Q,E]=eig(B)を求めよ。ただし、B(1,1)=1,B(6,6)=1である。固有値を並べたベクトルeを２*ones(1,6)-2*cos([0:5]*pi/6)により定義し  
E = diag(e)であることを確かめよ。  
DCT = cos([.5:5.5]'*[0:5]*pi/6)/sqrt(3)を要素とする（極めて重要な）離散余弦変換を生成するにはQをどのようにすれば良いか？

$K$での固有関数は$y(x)=coskπx$  
$Q_{i,j} = cos(n+\frac{1}{2})\frac{k}{n}π$

In [ ]:
n=6
B_n = toeplitz([2, -1]+[0]*(n-2))
B_n[0,0]=1
B_n[n-1,n-1,]=1
l3,Q3 = np.linalg.eig(B_n)
L = np.eye(6)*l3

a  = (np.ones((1,6)))
b = np.array([0,1,2,3,4,5])
c  = np.cos((np.pi/6)*b)
e = 2*a - 2*c

a2 = np.dot(np.diag([0.5,1.5,2.5,3.5,4.5,5.5]),np.ones((6,1)))
b2 = np.array(([0,1,2,3,4,5]))
c2=a2*b2
DST2 = np.cos(c2*(np.pi/6))/np.sqrt(3)

print(l3)
print(e)


## 問題1-5-6

自由端-固定端の行列$T = T_6$は左上隅の要素が$T(1,1)=1$である。その固有値は$2-2cos[(k-\frac{1}{2}π)/π/6.5]$であることを確かめよ.  
行列cos([.5:5.:]'*[.5:5.5]*pi/6.5)/sqrt(3.25)はTの単位固有ベクトルを列ベクトルとしてもつはずである。  
Q'*QおよびQ'TQを計算してみよ


$T$での固有関数は$y(x)=cos(k+\frac{1}{2})πx$  
$Q_{i,j} = cos(n+\frac{1}{2})\frac{k}{(n+\frac{1}{2})}π$

In [ ]:
#1-5-6
n=6
T_n = toeplitz([2, -1]+[0]*(n-2))
T_n[0,0]=1
l,Q = np.linalg.eig(T_n)
print(l)
a  = (np.ones((1,6)))
b = np.array([0.5,1.5,2.5,3.5,4.5,5.5])
c  = np.cos((np.pi/6.5)*b)
e = 2*a - 2*c
print(e)

a2 = np.dot(np.diag([0.5,1.5,2.5,3.5,4.5,5.5]),np.ones((6,1)))
b2 = np.array(([0.5,1.5,2.5,3.5,4.5,5.5]))
c2=a2*b2
QT = np.cos(c2*(np.pi/6.5))/np.sqrt(3.25)
print(np.dot(QT,QT.T))
print(np.dot(np.dot(QT,T_n),QT))

## 問題 1-5-7

フーリエ行列$F_4$の列ベクトルは巡回行列$C=C_4$の固有ベクトルである。しかし、[Q,E]=eig(C)としても$Q=F_4$は得られない。Qの列のどのような線形結合を作れば、$F_4$の列が得られるか？  
Eの中に重複固有値があることに注意すること

この行列は実数の直行する固有ベクトル（離散正弦及び離散余弦）
なので
固有ベクトルとして複素指数関数を用いる。

In [10]:
n=4
C_n = toeplitz([2, -1]+[0]*(n-2))
C_n[0,n-1]=-1
C_n[n-1,0,]=-1
l,Q = np.linalg.eig(C_n)
print(C_n)
print(l)
print(Q)

[[ 2 -1  0 -1]
 [-1  2 -1  0]
 [ 0 -1  2 -1]
 [-1  0 -1  2]]
[ -2.22044605e-16   2.00000000e+00   4.00000000e+00   2.00000000e+00]
[[  5.00000000e-01   7.07106781e-01  -5.00000000e-01   2.77555756e-17]
 [  5.00000000e-01  -2.02962647e-16   5.00000000e-01  -7.07106781e-01]
 [  5.00000000e-01  -7.07106781e-01  -5.00000000e-01   2.86262916e-16]
 [  5.00000000e-01   1.02348685e-16   5.00000000e-01   7.07106781e-01]]


## 問題1-5-8

$K_n$n個の固有値$2-2cos\frac{kπ}{n+1}$を加えるとトレース2+2.....+2になることを示せ
### 解答
$K_n$のn個の固有値は$2-2cos\frac{kπ}{n+1}(k = 1,2,...,n+1)$となる。  
よって固有値の和は$\sum_{k=1}^{n}2-2cos(\frac{kπ}{n+1})$となる。  
$cos(\frac{jπ}{n+1})=-cos(\frac{jπ}{n+1}-\frac{π}{2})$  
$cos(\frac{jπ}{n+1})=-cos(\frac{(j+\frac{n+1}{2})π}{n+1})$  
よって$\sum_{k=1}^{n}-2cos(\frac{kπ}{n+1})=0$となることより  
$\sum_{k=1}^{n}2-2cos(\frac{kπ}{n+1})=\sum_{k=1}^{n}2=2n$となる


## 問題1-5-9

$K_3$と$B_4$は両方とも4×3の交代差分行列$Δ$から生成されるので、同じ非ゼロ固有値をもつ  
$K_3＝Δ^TΔ$及び$B_4=ΔΔ^T$を示せ。  
$K_3$の固有値は$Δ$の特異値の２乗である

In [ ]:
#交代差分行列
n=15
a=np.ones([1,n])
Db= sp.spdiags(np.r_[-a, a], [-1,0],4,3).toarray()
Db

K3 = np.dot(Db.T,Db)
B4 = np.dot(Db,Db.T)
print(Db)
print(K3)
print(B4)


## 問題1-5-10

次の２つの行列を$A = SΛS^{-1}$と分解せよ。また$A ^2= SΛ^2S^{-1}$が成り立つことを示せ。

$A = \begin{bmatrix}
1 & 2 \\
0 & 3 
\end{bmatrix}$
$A = \begin{bmatrix}
1 & 1 \\
2 & 2 
\end{bmatrix}$

In [ ]:
#1-5-10
A1 = np.array([[1,2],[0,3]])
A2 = np.array([[1,1],[2,2]])
l1, S1 = np.linalg.eig(A1)
inv_S1 = np.linalg.inv(S1)
L1 =np.eye(2)*l1
print(np.dot(np.dot(S1,L1),inv_S1))
AA1 = np.dot(A1,A1)
print(AA1)
print(np.dot(np.dot(S1,L1),np.dot(L1,inv_S1)))


l2, S2 = np.linalg.eig(A2)
inv_S2 = np.linalg.inv(S2)
L2 =np.eye(2)*l2
print(np.dot(np.dot(S2,L2),inv_S2))
AA2 = np.dot(A2,A2)
print(AA2)
print(np.dot(np.dot(S2,L2),np.dot(L2,inv_S2)))


## 問題1-5-11

もし$A = SΛS^{-1}$ならば$A^{-1}=()$でる。$A^3$の固有ベクトルは次のうちどちらか？  
同じSの列ベクトル or 異なるベクトル

### 解答
$A = SLS^{-1}$とすると$A^{-1} = SL^{-1}S^{-1}$  
$A^3 = SL^3S^{-1}$となるので$A^3$の固有ベクトルは$S$の列ベクトルである

## 問題1-5-12

Aが固有値$λ_1=2$と対応する固有ベクトル$x_1 = \begin{bmatrix}1\\0 \end{bmatrix}$,及び$λ_2=5$と対応する　固有ベクトル$x_1 = \begin{bmatrix}1\\1 \end{bmatrix}$を持つとする。  
$SΛS^{-1}$を用いてAを求めよ。この同じ$λ$とxの組を持つ行列は他に存在しない。

In [ ]:
#1-5-12
x1 = np.array([1,0])
x2 = np.array([1,1])
L = np.array([[2,0],[0,5]])
S = np.array([x1,x2])
inv_S = np.linalg.inv(S)
A = (np.dot(np.dot(S,L),inv_S))
print(L)
print(S)
print(inv_S)
print(A)

## 問題1-5-13

$A=SΛS^{-1}$とする。$A+2I$の固有値行列は何か？また固有ベクトル行列は何か？  
$A+2I=(　)(　)(　)^{-1}$であることを確かめよ。

### 解答
固有値の計算は$det(A-λI)=0$を満たす$λ$である.  
よって$det(A+2I-λI_1)=0,(A-(λ_1-2)I)=0$を満たす$λ_1$は$λ+2$となる  
なので固有ベクトルは同じになる。  
そして$A+2I=S(Λ+2)S^{-1}$となる

In [ ]:
#1-5-13
A = np.array([[1,1],[2,2]])
A2 = A + 2*np.eye(2)
l2, S2 = np.linalg.eig(A2)
l2 = l2*np.eye(2)
inv_S2 = np.linalg.inv(S2)
print(A)
print(l2)
print(S2)
print(inv_S2)
A3 = (np.dot(np.dot(S2,l2),inv_S2))
A3

## 問題1-5-14

もしSの列ベクトル（すなわちAのn本の固有ベクトル）が線形独立ならば  
(a)Aは可逆 (b)Aは対角化可能　（c）Sは可逆

### 解答
Sの列ベクトルが線形独立であるならばAはn個のの異なる固有値をもつ

## 問題1-5-15

行列$A=\begin{bmatrix}3 & 1 \\0 & 3 \end{bmatrix}$は対角化可能でない。A-3Iの階数が＿だからである。  
Aは１本の固有ベクトルしか持たない。Aが２本の固有ベクトルをもち対角化可能であるようにするためにはAのどの要素を変えればよいのか？

### 解答
＿＝１
対角化できる条件としてはn個の異なる固有値を持つことがあるのでAの対角要素を変えれば固有値を二つもとことが可能になる

In [ ]:
#1-4-15
#対角化できる条件としてはn個の異なる固有値を持つこと

A14 = np.array([[3,1],[0,3]])
l14, S14 = np.linalg.eig(A14)
print(l14)
A14_2 = np.array([[3,1],[0,4]])
l14_2, S14_2 = np.linalg.eig(A14_2)
print(l14_2)

## 問題1-5-16
$k→∞$の時、$A^k=SΛS^{-1}$がゼロ行列に近づくのは、全ての$λ$の絶対値が＿よろ小さい場合であり、そも場合に限る。次の行列のうち$A^k→０$となるのはどれか？  
$A_1=\begin{bmatrix}0.6 & 0.4 \\0.4 & 0.6 \end{bmatrix}$  
$A_2=\begin{bmatrix}0.6 & 0.9 \\0.1 & 0.6 \end{bmatrix}$  
$A_3=K_3$

### 解答
ある任意の行列Aに置いて対角化が可能な場合その全ての固有値の絶対値が１より小さいならばAのn乗は０に近く


In [ ]:
#1-5-16
A161 = np.array([[0.6,0.4],[0.4,0.6]])
A162 = np.array([[0.6,0.9],[0.1,0.6]])
n=3
K_n  =toeplitz([2, -1]+[0]*(n-2))
A163=K_n
l161, S161 = np.linalg.eig(A161)
l162, S162 = np.linalg.eig(A162)
l163, S163 = np.linalg.eig(A163)
print(l161)
print(l162)
print(l163)



## 問題1-5-17

問題１６の$A_1$を対角化する$Λ$と$S$を求めよ。以下の$u_0$に対し $A^{10}u_0$はどうなるか？  
$u_0=\begin{bmatrix}1 \\ 1 \end{bmatrix}$
$u_0=\begin{bmatrix}1 \\ -1 \end{bmatrix}$
$u_0=\begin{bmatrix}2 \\ 0 \end{bmatrix}$


In [ ]:
#1-5-17
A161 = np.array([[0.6,0.4],[0.4,0.6]])
l161, S161 = np.linalg.eig(A161)
l161 = l161*np.eye(2)
inv_S161 = np.linalg.inv(S161)
print(l161)
print(S161)
A17 = np.dot(np.dot(S161,np.power(l161,10)),inv_S161)
print(A17)

u1 = np.array([1,1])
u2 = np.array([1,-1])
u3 = np.array([2,0])

print(np.dot(A17,u1))
print(np.dot(A17,u2))
print(np.dot(A17,u3))

## 問題1-5-18

Aを対角化して$A^k=SΛS^{-1}$を計算することにより$A^k$に対応する次の公式を示せ。  
$A=\begin{bmatrix}2 & 1 \\1 & 2 \end{bmatrix}$
$A^k=\frac{1}{2}\begin{bmatrix}3^k+1 &3^k-1  \\3^k-1 & 3^k+1 \end{bmatrix}$

In [ ]:
#1-5-18

A18 = np.array([[2,1],[1,2]])
l18, S18 = np.linalg.eig(A18)
l18 = l18*np.eye(2)
inv_S18 = np.linalg.inv(S18)

print(l18)
print(S18)


print(np.dot(np.dot(S18,np.power(l18,2)),inv_S18))
print(np.dot(np.dot(S18,np.power(l18,3)),inv_S18))
print(np.dot(np.dot(S18,np.power(l18,4)),inv_S18))
print(np.dot(np.dot(S18,np.power(l18,5)),inv_S18))


## 問題 1-5-19

Aを対角化して$A^k=SΛS^{-1}$を計算することにより$B^k$が$3^k$と$2^k$を用いてる技のようにかけることを示せ

$B=\begin{bmatrix}3& 1 \\0 & 2 \end{bmatrix}$
$B^k=\frac{1}{2}\begin{bmatrix}3^k &3^k-2^k  \\0 & 2^k\end{bmatrix}$

In [ ]:
#1-5-19

A19 = np.array([[3,1],[0,2]])
l19, S19 = np.linalg.eig(A19)
l19 = l19*np.eye(2)
inv_S19 = np.linalg.inv(S19)
print(np.dot(np.dot(S19,np.power(l19,2)),inv_S19))
print(np.dot(np.dot(S19,np.power(l19,3)),inv_S19))
print(np.dot(np.dot(S19,np.power(l19,4)),inv_S19))
print(np.dot(np.dot(S19,np.power(l19,5)),inv_S19))

## 問題　1-5-20
$A=SΛS^{-1}$とする$A=SΛS^{-1}$.両方の行列式を取ることによりdetA = $λ_1λ_2,,,λ_n$となることを示せ。この簡単な証明はAが＿の場合のみ適用できる。

### 解答
行列Aが対角行列の時、Aの行列式は固有値の積となる

## 問題 1-5-21

GHとHGの対角要素をそれぞれ足し合わせることにより、traceGH = traceHGを示せ。  
$G=\begin{bmatrix}a& b \\c & d \end{bmatrix}$
$H=\begin{bmatrix}e& f \\g & h \end{bmatrix}$  
G=S,H=$ΛS_{-1}$を選ぶと$SΛS^{-1}=A$は$ΛS^{-1}S=A$と同じトレースを持つことになる。  
したがってトレースは固有との和である。

### 解答
$GH=\begin{bmatrix}ae+bg&af+bh \\ce+dg & cf+dh \end{bmatrix}$
$HG=\begin{bmatrix}ae+cf&be+df \\ag+ch & bg+dh \end{bmatrix}$  
$traceGH = traceHG = ae+bg+cf+dh$  


## 問題 1-5-22

$A = SΛS^{-1}$を積$(A-λ_1I)(A-λ_2I),,,,(A-λ_nI)$に代入し$(Λ-λ_1)(Λ-λ_2),,,,(Λ-λ_n)$がゼロ行列となることを示せ。  
これは多項式$p(λ)=det(A-λI)$のλにAを代入したと見ることができる。
このケーリーハミルトンの定理は$p（A）$がゼロ行列となることを言っている。

### 解答
Aがある固有値λをもつ時A-Iの固有値はλ-1となる。
$(A-λ_1I)(A-λ_2I),,,,(A-λ_nI)=S(Λ-λ_1)S^{-1}S(Λ-λ_2)S^{-1}......S(Λ-λ_n)S^{-1}$となる。  
$(A-λ_iI)$ではi列目の要素がゼロになる。  
このことから$(Λ-λ_1)(Λ-λ_2),,,,(Λ-λ_n)$がゼロ行列となる


## 問題1-5-23
$u = e^{λt}x$が次の方程式の解となるような$λ$と$x$を定めよ  
$\frac{du}{dt}=\begin{bmatrix}4& 3 \\0 & 1 \end{bmatrix}u$  
線形結合$u=e_1^{λ_1t}x_1+e_2^{λ_2t}x_2$をどのように作ればu(0)=(5,-2)から出発する解が作れるか？

### 解答
固有値が１と４なので連立方程式の解は $u(t) = C_1e^t + C_2e^{4t}$  
$u(0)=(5,-2)$の初期条件を用いてCとDを求めると$C=-2,D=5$  
よって$u(t) = -2e^t + 5e^{4t}$

In [ ]:
#1-5-23
A23 = np.array([[4,3],[0,1]])
l23, S23 = np.linalg.eig(A23)
print(l23)
B23 = np.array([[0,1],[1,0]])
inv_B = np.linalg.inv(B23)
C = np.dot(inv_B,np.array([5,-2]))
print(C)


## 問題 1-5-24

スカラーの方程式$y''=5y'+4y$をベクトルの方程式$u = (y,y')$に書き直した時の$A$を求めよ。  
Aの固有値は何か？$y=e^{λt}$を$y''=5y'+4y$に代入して$λ_１$と$λ_２$を決める方法も試してみよ。
$\frac{du}{dt}=\begin{bmatrix}y'\\y'' \end{bmatrix}=[]\begin{bmatrix}y \\y' \end{bmatrix}=Au$


### 解答
$\begin{bmatrix}y'\\y'' \end{bmatrix}=\begin{bmatrix}5&4\\1&0 \end{bmatrix}\begin{bmatrix}y \\y' \end{bmatrix}=Au$  


In [ ]:
#1-5-24

print('y’’= 5y’+ 4y')
A24 = np.array([[5,4],[1,0]])
l24, S24 = np.linalg.eig(A24)
print(A24)
print(l24)
x = symbols('x')
eq1 = np.power(x,2)-5*(np.power(x,1))-4
solve([eq1],[x])

## 問題 1-5-25

うさぎとオオカミの個体数を記述する次の方程式はうさぎが早く増えること（6r）の項よりとオオカミによってその数が減ること（-2wの項より）を表している。行列Aを求め、その固有値と固有ベクトルを求めよ。  
$\frac{dr}{dt}=6r-2w,\frac{dw}{dt}=2r+w$  
r(0)=w(0)=30の時、時刻tにおけるそれぞれの個体数はどうなるか？長い時間の後,ウサギとオオカミの比は１対２となるか？それとも２対１か？

### 解答
$\begin{bmatrix}r'\\w' \end{bmatrix}=\begin{bmatrix}6&-2\\2&1 \end{bmatrix}\begin{bmatrix}r\\w \end{bmatrix}=Au$  
A25の固有値が2と5なので連立方程式の解は  
$u(t) = Ce^{2t}x_1 + De{5t}x_2$  
$\begin{bmatrix}r(t)\\w(t) \end{bmatrix}=\begin{bmatrix}2&1\\1&2 \end{bmatrix}\begin{bmatrix}Ce^{2t}\\ De^{5t}\end{bmatrix}$  
u(0) = (30,30)という条件からCとDを求めるとC＝D＝１0；
よって  
$r(t) = 20e^{2t} + 10e^{5t}$  
$w(t) = 10e^{2t} + 20e^{5t}$

よってうさぎと狼の比は１：２になる

In [ ]:
#1-5-25

A25 = np.array([[6,-2],[2,1]])
l25, S25 = np.linalg.eig(A25)
print(l25)
print(S25)
B25 = np.array([[1,1],[1,-1]])
inv_B = np.linalg.inv(S25)
C = np.dot(inv_B,np.array([30,30]))
print(inv_B)
print(C)


## 問題 1-5-26

$y=e^{λt}$を$y''=6y'-9y$に代入し、λ=3が重解であることを示せ。ここで困難が生じる。
$e^{3t}$の他にもう一つの解が必要だからである。行列で書いた方程式は次のようになる。
$\frac{d}{dt}\begin{bmatrix}y\\y' \end{bmatrix}=\begin{bmatrix}0&1 \\-9&6 \end{bmatrix}\begin{bmatrix}y\\y' \end{bmatrix}$  
この行列は固有値λ=3,3を持ち固有ベクトルは１本しか持たないことを示せ。ここでもまた困難が生じる。もう一つの解が$y=te^{3t}$で与えられることを示せ。


In [3]:
#1-5-26
x = symbols('x')
eq1 = np.power(x,2)-6*(np.power(x,1))+9
solve([eq1],[x])
A26=np.array([[0,1],[-9,6]])
l26,S26 = np.linalg.eig(A26)
S26

NameError: name 'symbols' is not defined

## 問題1-5-27

$A$と$A^T$が同じ固有値を持つのはなぜか説明せよ。Aがマルコフ行列である時、λ=1は常にその固有値であることを示せ。これは$A^T$の各行の和が１でそれゆえ＿というベクトル$A^T$の固有値ベクトルとなるからである。

### 解答
ある行列の固有値を求める時は$｜A - λI｜= 0　$となる$λ$を固有値とする。固有値の計算の際に関わってくるのはAの対角要素だけである。$A$も$A^T$も対角要素が同じなので固有値の値は同じになる



M = np.array([[0.8,0.4],[0.2,0.6]])
lM,SM=np.linalg.eig(M)
Mt = M.T
lMt,SMt=np.linalg.eig(Mt)
print(Mt)
print(SM)
print(SMt)

In [ ]:
## 問題1-5-28

次の行列AとTの固有値と単位ベクトルを求めよ。
またトレースを使って検算を行え
$A=\begin{bmatrix}1& 1&1 \\ 1&0&0 \\ 1&0&0 \end{bmatrix}$
$T=\begin{bmatrix}1& -1 \\-1 & 2 \end{bmatrix}$

In [ ]:
#1-5-28
A28 = np.array([[1,1,1],[1,0,0],[1,0,0]])
T28 = np.array([[1,-1],[-1,2]])
l28,S28 = np.linalg.eig(A28)
lt28,St28 = np.linalg.eig(T28)
print(l28)
print(S28)
print(lt28)
print(St28)


## 問題1-5-29

ここに実行列の固有値は実であることの簡単な証明がある。  
$Ax=λx$より$x^TAx=λx^Tx$であるから$λ=\frac{x^TAx}{x^Tx}$は実数となる  
この推論における欠陥ー正当化できない隠れた仮定ーを見つけよ

In [ ]:
#1-5-29
print(np.array([[0,1],[1,0]]))
print(np.array([[1,0],[0,1]]))
print(np.array([[x,a],[a,-x]]))

## 問題1-5-30

直行かつ対称であるような2×2行列全てを求めよ。これらの行列の固有値となりうる２つの数は何か？

### 正解

$A=\begin{bmatrix}a& b \\c & d \end{bmatrix}$とすると  
直行の条件は$ab+cd=0$　　
対称の条件は$b=c$となる  
この両方の条件を満たす２×２の行列は
$\begin{bmatrix}a& b \\b & -a \end{bmatrix}$となる。  
よってその固有値は$λ=a,-a$となる

## 問題1-5-31

微分方程式$u''=λu$の固有関数$y(x)=sinkπx$を求めるためには、$y=e^{ax}$を方程式に代入するという方法もあった。こうすると、$-a^2e^{ax }=λe^{ax}$より$a=i\sqrt{λ}$ or $-i\sqrt{λ}$がえられる。完全解は$y(x)=Ce^{i\sqrt{λ}x}+De^{-i\sqrt{λ}x}$であり$y(0)=0$より$C+D=0$となる。これより、$y(x)$は正弦関数に簡単かされる。  
$y(x)=C(e^{ i\sqrt{λ}x}-e^{i\sqrt{λ}x})=2iCsin\sqrt{λ}x$
$y(1)=0$より$sin\sqrt{λ}＝０$となる。したがって$\sqrt{λ}$はπの整数倍kπ出なくてはならず、前と同様に$λ=k^2π^2$となる。この解き方を、$y'(0)=y'(1)=0$の場合、及び$y'(0)=y(1)=0$の場合にもやってみよ。


### 解答

$y(x)=Ce^{i\sqrt{λ}x}+De^{-i\sqrt{λ}x}$より  
$y'(x)=i\sqrt{λ}Ce^{i\sqrt{λ}x}-i\sqrt{λ}De^{-i\sqrt{λ}x}$である.   
  
$y'(0)=y'(1)=0$の場合  
$y'(0)=i\sqrt{λ}C-i\sqrt{λ}D=0,C=D$  
$y(x)=C(e^{i\sqrt{λ}x}-e^{-i\sqrt{λ}x})$  
$y(x)=C(e^{ i\sqrt{λ}x+i\sqrt{λ}x})=2iCcos\sqrt{λ}x$  
$y'(1)=2i\sqrt{λ}Csin\sqrt{λ}=0$より$\sqrt{λ}=0$であるため$λ=k^2π^2$となる。
Bの場合の固有関数
  
  
$y'(0)=y(1)=0$の場合
$y'(0)=i\sqrt{λ}C-i\sqrt{λ}D=0,C=D$  
$y(x)=C(e^{i\sqrt{λ}x}-e^{-i\sqrt{λ}x})$  
$y(x)=C(e^{ i\sqrt{λ}x+i\sqrt{λ}x})=2iCcos\sqrt{λ}x$  
$y(1)=2iCcos\sqrt{λ}=0$より $λ=(k+\frac{1}{2})^2π^2$となる。
Tの場合の固有関数

## 問題 1-5-32

以下の６つの行列についてeigshowでxとAxを追跡してみよ。実固有ベクトルは何本あるか？
$A = \begin{bmatrix}2& 0 \\0 & 1 \end{bmatrix}$
 $\begin{bmatrix}2& 0 \\0 & -1 \end{bmatrix}$
 $ \begin{bmatrix}0& 1 \\1 & 0 \end{bmatrix}$
 $\begin{bmatrix}0& 1 \\-1 & 0 \end{bmatrix}$
 $\begin{bmatrix}1& 1 \\1 & 1 \end{bmatrix}$
 $\begin{bmatrix}1& 1 \\0 & 1 \end{bmatrix}$

## 問題　1-5-33

Scarymatlabは丸誤差が対称性を壊した場合に何が起こるかを示す。
