使用するライブラリのインポート

In [12]:
import numpy as np
import scipy.linalg as linalg
from matplotlib import pyplot
import scipy.sparse as sp
import scipy.sparse.linalg as spla
import math
from numpy.random import rand

### 1.1 1
$T_3$および$T_4$の逆行列の逆行列は次のようになる。
 
$$
 T_3^{-1} = 
\begin{pmatrix} 3 & 2 & 1 \\ 2 & 2 & 1 \\ 1 & 1 & 1 \end{pmatrix}
 ,  T_4^{-1} = 
\begin{pmatrix} 4 &3 & 2 & 1\\ 3 &3 & 2 & 1 \\ 2 & 2 & 2 & 1 \\ 1 &1 & 1 & 1 \end{pmatrix}
$$
その形から$T_5$を予測し、$T_5^{-1}$をかけてみよ。

$T_n^{-1}$において、対角要素以下の要素を与える簡単な式を求めよ。次に、対角要素以上の要素を与える簡単な式を求めよ。

#### 解答
まず$T_5^{-1}$の形を予想する。

In [13]:
T_5_inv = np.asarray([[5, 4, 3, 2, 1],[4, 4, 3, 2, 1],[3, 3, 3, 2, 1],[2, 2 , 2, 2, 1], [1, 1, 1, 1, 1]])
print(T_5_inv)

[[5 4 3 2 1]
 [4 4 3 2 1]
 [3 3 3 2 1]
 [2 2 2 2 1]
 [1 1 1 1 1]]


さらに、$T_5$は

In [14]:
T_5 = linalg.toeplitz(np.asarray([2,-1,0,0,0]))
T_5[0,0]=1
print(T_5)

[[ 1 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]]


これに$T_5$をかけてみると、

In [15]:
print(T_5.dot(T_5_inv))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


となり、単位行列が生成されたことから、これは$T_5$の逆行列であることがわかる。

$T_n^{-1}$において、対角要素以下の要素を与える式は、行番号をi、列番号をjとすれば
$t_{ij}=n-(i-1)$

対角要素以上の要素を与える式は、
$t_{ij}=n-(j-1)$
である。

### 1.1.2
$$
U^{-1} = 
\begin{pmatrix} 1 & -1 & 0 \\ 0 & 1 & -1 \\ 0 & 0 & 1 \end{pmatrix}^{-1}
  = 
\begin{pmatrix} 1 & 1 & 1\\ 0& 1 & 1 \\ 0 & 0 & 1\end{pmatrix}\tag{2}
$$
式(2)のUと$U^{-1}$をつかって、次の３ステップに従って$T_3^{-1}$を計算せよ。
1. $T_3 = U^{T}U$を確認せよ。ここで、Uは主対角線上に1、その1本上の対角線上に-1が並んだ行列である。その天地$U^{-1}$は下三角行列である。
2. $U^{-1}$を上三角部分（主対角線を含む）がすべて1の行列とする時、$UU^{-1}=I$を確認せよ。
3. $U^{T}U$の逆行列を計算し、$T_3^{-1}= (U^{-1})(U^{-1})^{T}$を求めよ。

#### 解答

$T_3$は、

In [16]:
T_3 = (linalg.toeplitz(np.asarray([2,-1,0])))
T_3[0,0]=1
print(T_3)

[[ 1 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]


一方で、$U$と$U^{T}$は

In [17]:
U_3 = linalg.toeplitz(np.asarray([1,-1,0]))*np.transpose(np.tri(3))
U_3_t = np.transpose(U_3)
print(U_3)
print(U_3_t)

[[ 1. -1.  0.]
 [-0.  1. -1.]
 [ 0. -0.  1.]]
[[ 1. -0.  0.]
 [-1.  1. -0.]
 [ 0. -1.  1.]]


であり、$UU^{T}$を確認すると、

In [18]:
print(U_3_t.dot(U_3))

[[ 1. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]


よって、$UU^{T}=T_3$が示された。

次に、$UU^{-1}$を計算する。$U$と$U^{-1}$はそれぞれ、

In [19]:
U_3_inv = np.transpose(np.tri(3))
print(U_3)
print(U_3_inv)

[[ 1. -1.  0.]
 [-0.  1. -1.]
 [ 0. -0.  1.]]
[[ 1.  1.  1.]
 [ 0.  1.  1.]
 [ 0.  0.  1.]]


ところで、$U$は一階微分に相当する演算子と考えることができる。したがって、その逆演算に相当する$U^{-1}$は一階の積分に相当すると考えられる。
よって、$UU^{-1}$は全体としてなんの作用も起こさない演算子、単位行列$I$として作用すると予想される。実際に計算してみると、

In [20]:
print(U_3.dot(U_3_inv))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


となる。

よって、$UU^{-1}=I$が示された。

直感的には、微分演算は定数項の情報が保存されないため、$UU^{-1}$が全体として単位行列になるのはおかしいのではないか？と思うところである。
しかし今回の行列を使った微分というのは離散的で、演算対象のデータの端の値については微分ができないことがあり、実際$U$を見てみると一番下の行は微分になっていない。この部分は微分の役割をしない代わりに、定数項の部分、微分方程式であれば初期条件に相当する情報を保持する役割を持つと考えられる。よって$UU^{-1}=I$は正しいことが分かる。

### 1.1.3
和文行列$S$を生成し、積$U*S$を計算し、$S=U^{-1}$を確認せよ。

#### 解答
和文行列$S$は、

In [21]:
S_5=np.triu(np.ones(5))
print(S_5)

[[ 1.  1.  1.  1.  1.]
 [ 0.  1.  1.  1.  1.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  1.]]


$U*S$を計算すると、

In [22]:
U_5 = linalg.toeplitz(np.asarray([1,-1,0,0,0]))*np.transpose(np.tri(5))
print(U_5.dot(S_5))

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


となり、結果が単位行列であることから$S$が$U$の逆行列であることがわかる。実際、$U^{-1}$は

In [23]:
print(linalg.inv(U_5))

[[ 1.  1.  1.  1.  1.]
 [ 0.  1.  1.  1.  1.]
 [ 0.  0.  1.  1.  1.]
 [ 0.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  1.]]


である。したがって、$S=U^{-1}$である。

### 1.1.4
任意のnについて、$S_n=U_n^{-1}$は上三角部分が全て1の行列であるが、n=4の時$S_nS_n^{T}=T_4^{-1}$となることを確かめよ。また、$S_nS_n^{T}$は明らかに対称行列であるが、これはなぜか。
#### 解答
$S_4$と$S_4^{T}$とその積$S_4S_4^{T}$はそれぞれ、

In [24]:
S_4=np.triu(np.ones(4))
S_4_tr= np.transpose(S_4)
print(S_4)
print(S_4_tr)
print(S_4.dot(S_4_tr))

[[ 1.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 0.  0.  1.  1.]
 [ 0.  0.  0.  1.]]
[[ 1.  0.  0.  0.]
 [ 1.  1.  0.  0.]
 [ 1.  1.  1.  0.]
 [ 1.  1.  1.  1.]]
[[ 4.  3.  2.  1.]
 [ 3.  3.  2.  1.]
 [ 2.  2.  2.  1.]
 [ 1.  1.  1.  1.]]


であり、$S_4S_4^{T}=T_4^{-1}$であることが確認できる。対称行列となる理由であるが、まず$S_nS_n^{T}$の個々の成分に注目する。
$S_n$のi行j列の成分を$(S_n)_{ij}$とおくと、$(S_nS_n^{T})_{ij}=\sum_{k=1}^{n}(S_n)_{ik}(S_n^{T})_{kj}=\sum_{j=1}^{n}(S_n)_{ik}(S_n)_{jk}$

この式の右辺では、$i,j$は交換しても等しい式となっている。従って、左辺の$i,j$を入れ替えても要素の値が変わらないから、$S_nS_n^{T}$は対称行列である。

### 1.1.5
$$
 K_3^{-1} = 
\frac{1}{4}\begin{pmatrix} 3 & 2 & 1 \\ 2 & 4 & 2 \\ 1 & 2 & 3 \end{pmatrix}
 ,  K_4^{-1} = 
\frac{1}{5}\begin{pmatrix} 4 &3 & 2 & 1\\ 3 & 6 & 4 & 2 \\ 2 & 4 & 6 & 3 \\ 1 &2 & 3 & 4 \end{pmatrix}
$$
$K_3$および$K_4$の逆行列は$\frac{1}{det}=\frac{1}{4}, \frac{1}{5}$という分数の因子を持つ。

まず$K=K_5$の行列式を推測してみよ。次に、$det(K)とinv(K)$を求め。$det(K)*inv(K)$を計算せよ。
#### 解答
まず、$K_5$は、

In [25]:
K_5  = linalg.toeplitz([2, -1, 0, 0, 0])
print(K_5)

[[ 2 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]]


である。また、$det(K_5)$は、$\frac{1}{6}$と予想され、実際に計算すると

In [26]:
print(linalg.det(K_5))

6.0


となり予想通りである。
$det(K)*inv(K)$を計算すると、

In [27]:
print(linalg.det(K_5)*linalg.inv(K_5))

[[ 5.  4.  3.  2.  1.]
 [ 4.  8.  6.  4.  2.]
 [ 3.  6.  9.  6.  3.]
 [ 2.  4.  6.  8.  4.]
 [ 1.  2.  3.  4.  5.]]


となり、要素が整数になっている。

### 1.1.6
（挑戦問題）
$K_4^{-1}$の下三角部分について、$i,j$要素を与える式を求めよ。
#### 解答
$(K_n)_{i,j}=(n-(i-1))j$


### 1.1.7
列ベクトル$u$と行ベクトル$v^{T}$との積は、階数1の行列 $uv^{T}$となる。この行列の全ての列は$u$の定数倍であり、全ての行は$v^{T}$の定数倍である。
$T_4^{-1}-K_4^{-1}$は階数1の行列である。
$$
 T_4^{-1} - K_4^{-1} = 
\frac{1}{5}\begin{pmatrix} 16 & 12 & 8 & 4 \\ 12 & 9 & 6 & 3 \\ 8 & 6 & 4 & 2 \\ 4 & 3 & 2 & 1 \end{pmatrix}
  = 
\frac{1}{5}\begin{pmatrix} 4 \\ 3 \\ 2 \\ 1 \end{pmatrix}\begin{pmatrix} 4 & 3 &  2 &  1 \end{pmatrix}
$$
$K_3 - T_3$を$uv^{T}$という形に書け。また、$T_3^{-1}　- K_3^{-1}$についても同様の式を予測せよ。

#### 解答
まず、$K_3 - T_3$を計算し、そこから$uv^{T}$に分解することを考える。

$K_3, T_3, K_3 - T_3$はそれぞれ

In [ ]:
K_3  = linalg.toeplitz([2, -1, 0])
T_3 = (linalg.toeplitz(np.asarray([2,-1,0])))
T_3[0,0]=1
print(K_3)
print(T_3)
print(K_3 - T_3)

この結果から、$uv^{T}$に分解した場合、
$$u=\begin{pmatrix} 1\\ 0 \\ 0 \end{pmatrix}\\
v^{T}=\begin{pmatrix} 1 & 0 &  0 \end{pmatrix}$$
が一つ考えられる。
また、$T_3^{-1}　- K_3^{-1}$に関して同様の検討をする。
$T_3^{-1}　,  K_3^{-1}, T_3^{-1}　- K_3^{-1}$はそれぞれ

In [ ]:
print(linalg.inv(K_3))
print(linalg.inv(T_3))
print(linalg.inv(K_3) - linalg.inv(T_3))

この結果から、$T_3^{-1}　- K_3^{-1}$を4倍すると、

In [ ]:
print(4*(linalg.inv(K_3) - linalg.inv(T_3)))

この結果から$uv^{T}$に分解した場合、
$$u=\frac{-1}{4}\begin{pmatrix} 3\\ 2 \\ 1 \end{pmatrix}\\
v^{T}=\begin{pmatrix} 3 & 2 &  1 \end{pmatrix}$$
が考えられる。

### 1.1.8
(a)　問題7に基づき、$T_5^{-1}　- K_5^{-1}$の下三角部分の$i,j$要素を予想せよ。
(b) この結果を問題1の答え（$T_5^{-1}$の上三角要素を与える公式）から差し引け。これはK_5^{-1}に対する（あまり単純でない）公式を与える、

#### 解答
$T_5^{-1}　- K_5^{-1}$の下三角要素の式について考える。
$T_5^{-1},  K_5^{-1}, T_5^{-1}　- K_5^{-1}$
をそれぞれ確認すると、


In [ ]:
T_5 = linalg.toeplitz(np.asarray([2,-1,0,0,0]))
T_5[0,0]=1
T_5_inv = linalg.inv(T_5)
K_5  = linalg.toeplitz([2, -1, 0, 0, 0])
K_5_inv = linalg.inv(K_5)
print(T_5_inv)
print(K_5_inv)
print(T_5_inv - K_5_inv)
print(6*(T_5_inv - K_5_inv))

また$T_5^{-1}　- K_5^{-1}$について定数倍として6をかけると、

よって、$(T_n^{-1}　- K_n^{-1})_{ij} = \frac{1}{n+1}(n-(i-1))(n-(j-1)j)^2$
が導かれた。また、これを問題1の$(T_5^{-1})_{ij}$から差し引くと、$(K_n^{-1})_{ij}$は
$(K_n^{-1})_{ij}=n-(i-1)-\frac{1}{n+1}(n-(i-1))(n-(j-1))^2$

### 1.1.9
例題1.1AにおいてBをCで置き換えて$e=\begin{pmatrix} 1 \\ 1 \\ 1 \\ 1 \end{pmatrix}$が$C_4$の全ての列ベクトルと直行することを示せ。
また、擬逆行列を用いて$u=pinv(C)*f$とすることで特異な行列Cを係数とした連立一次方程式$Cu=f=$\begin{pmatrix} 1 \\ -1 \\ 1 \\ -1 \end{pmatrix}$を解け。第五の方程式0=0を付け加える前と後で、それぞれ$u=C/e$とC/fを実行してみよ。
#### 解答
まず、Cと$e=\begin{pmatrix} 1 \\ 1 \\ 1 \\ 1 \end{pmatrix}$が直行することを示す。

In [ ]:
e_4=np.ones((4,1))
C_4 = linalg.toeplitz([2, -1, 0, -1])
print(e_4)
print(C_4)
print(np.transpose(e_4).dot(C_4))

In [ ]:
f_4 = np.empty((0,4))
f_4  = np.transpose(np.append(f_4, np.array([[1, -1, 1,-1]]), axis=0))

f_5 =np.empty((0,5))
f_5 = np.transpose(np.append(f_5, np.array([[1, -1, 1,-1, 0]]), axis=0))
print(f_5)

C_4_append0 = C_4
C_4_append0 = (np.append(C_4_append0, [[0, 0, 0, 0]], axis=0))
print(C_4_append0)

print(f_4)
print(linalg.det(C_4))
print(linalg.inv(C_4).dot(f_4))
print(linalg.solve(C_4, f_4))
print(linalg.pinv(C_4_append0).dot(f_5))
print(linalg.pinv(C_4).dot(f_4))



### 1.1.10
追加問題1.1Bのぶら下がり行列Hでは、$K_3$の最後の要素が1に変わっている。$H^{-1}=JT^{-1}J$を用いて逆行列を求めよ。また、$H=UU^{T}$と$H^{-1}=(U^{-1})^{T}U^{-1}$からも逆行列を求めてみよ。


#### 解答


In [ ]:
# 10 of 1.1
J_3 = np.fliplr(np.eye(3))
T_3 = (linalg.toeplitz(np.asarray([2,-1,0])))
T_3[0,0]=1
T_3_inv = np.linalg.inv(T_3)
H_inv = (J_3.dot(T_3_inv)).dot(J_3)
U_3 = linalg.toeplitz(np.asarray([1,-1,0]))*np.transpose(np.tri(3))
U_3_t = np.transpose(U_3)
U_3_inv = np.transpose(np.tri(3))
print(U_3)
print(U_3_t)
print('\n J*T_inv*J :\n', H_inv)
# Jを左からかけると上下反転、右からかけると左右反転になる

print('\n U_inv*U :\n', np.transpose(U_3_inv).dot(U_3_inv))
print(linalg.inv(U_3.dot(U_3_t)))
print((np.transpose(U_3_inv)).dot(U_3_inv))

### 1.1.11


#### 解答


In [ ]:

# 11 of 1.1
U_3_arb = np.transpose(np.tri(3))
print('\nU\n', U_3_arb)
print('\nJ*U\n', J_3.dot(U_3_arb))
print('\nU*J\n', U_3_arb.dot(J_3))
print('\nJ*U*J\n', (J_3.dot(U_3_arb)).dot(J_3))

よって$UJ$は北西　$JUJ$は南西

### 1.1.12


#### 解答


In [ ]:
# 12 of 1.1
C_4 = (linalg.toeplitz(np.asarray([2,-1,0,0])))*(np.ones(4) - np.fliplr(np.eye(4))) + np.fliplr((-1)*np.eye(4))
print('\nC\n',C_4)
LU = linalg.lu_factor(C_4)
L = (np.tri(4,4,-1)*(LU[0])) + np.eye(4)
U = np.transpose(np.tri(4))*(LU[0])
print('\nL\n',L)
print('\nU\n',U)

# 有限の桁数で計算しているからでは？

### 1.1.13
手計算により$C_4$をLU分解できるか。

#### 解答
手計算参照

### 1.1.14
$K_3$の対角要素2,2,2を　$\sqrt{2},\sqrt{2},\sqrt{2}$に変更せよ。この新しい行列Mの行列式を計算し、$Mu=0$を満たす非ゼロベクトルを求めよ。$Ku=(2-\sqrt{2})u$であり、$u$は$K$の固有値$2-\sqrt{2}$に属する固有ベクトルとなる。これはなぜかを説明せよ。

#### 解答


In [ ]:
# 14 of 1.1
K_3_sq2  = linalg.toeplitz([math.sqrt(2), -1, 0])
print(K_3_sq2)
print(linalg.det(K_3_sq2))
# 0になる

行列式は0になる。すなわち、$K$において固有値が$2-\sqrt{2}$であった場合の固有方程式の係数行列がMということである。

### 1.1.15
$Az, A^2, AB$を計算するには、それぞれ何回の実数の乗算が必要か。

#### 解答
$n^2, n^3, npm$

### 1.1.16
積$Ax$は行単位で計算することもできるし、列単位に計算することもできる。2つの方法で計算してみよ


#### 解答
$\begin{pmatrix} 2 & 3  \\ 4 & 5 \end{pmatrix}\begin{pmatrix}  1  \\ 2 \end{pmatrix}=
\begin{pmatrix} 2*1 + 3*2  \\ 4*1 + 5*2 \end{pmatrix}$

$\begin{pmatrix} 2 & 3  \\ 4 & 5 \end{pmatrix}\begin{pmatrix}  1  \\ 2 \end{pmatrix}=
1\begin{pmatrix} 2  \\ 4 \end{pmatrix} + 2\begin{pmatrix} 3 \\ 5 \end{pmatrix} \end{pmatrix}$

### 1.1.17
$Ax=b$において、$A$の列ベクトルが張る空間に$b$が含まれない例を与えよ。


#### 解答
$\begin{pmatrix} 1 & 2  \\ 2 & 4 \end{pmatrix}x=\begin{pmatrix} 1  \\ 1 \end{pmatrix}$


### 1.1.18
$\begin{pmatrix} 2 & 3  \\ 4 & 5 \end{pmatrix}\begin{pmatrix} 1 & 2  \\ 2 & 4 \end{pmatrix}=
\begin{pmatrix} 8 & *  \\ 14 & * \end{pmatrix}$

#### 解答
$\begin{pmatrix} 2 & 3  \\ 4 & 5 \end{pmatrix}\begin{pmatrix} 1 & 2  \\ 2 & 4 \end{pmatrix}=
\begin{pmatrix} 2  \\ 4 \end{pmatrix} \begin{pmatrix}1  & 2 \end{pmatrix}  + 2\begin{pmatrix} 3 \\ 5 \end{pmatrix}&2\begin{pmatrix} 2  \\ 4 \end{pmatrix} + 4\begin{pmatrix} 3 \\ 5 \end{pmatrix}=
\begin{pmatrix} 8 & 16  \\ 14 & 28 \end{pmatrix}$

### 1.1.19
行でも計算できる
$Bx=0$の解は$(AB)x=0$の解でもある、なぜか。

#### 解答
行列の積において可換則が成り立つから、$Bx=0$を満たす解は、$(AB)x=A(Bx)=A0=0$となる

### 1.1.20


#### 解答
$\begin{pmatrix} 2 & 3  \\ 4 & 5 \end{pmatrix}\begin{pmatrix} 1 & 2  \\ 2 & 4 \end{pmatrix}=
1\begin{pmatrix}2  \\ 4 \end{pmatrix} + 2\begin{pmatrix} 3 \\ 5 \end{pmatrix}+2\begin{pmatrix} 2  \\ 4 \end{pmatrix} + 4\begin{pmatrix} 3 \\ 5 \end{pmatrix}=
\begin{pmatrix} 8 & 16  \\ 14 & 28 \end{pmatrix}$

### 1.1.21
任意のn*n行列A,Bについて成り立つ等式（ただひとつ）はどれか。
$AB=BA, (AB)A=A(BA), (AB)B=B(BA), (AB)^2=A^2B^2$

#### 解答
$(AB)A=A(BA)$

### 1.1.22
疎行列形式で$K_1000$を入力した時、$Ku=e$となるような解を計算し、解をプロットせよ。

#### 解答
以下の通り。

In [ ]:
# 22 of 1.1
n=1000;
e=np.ones([1,n])
A = sp.spdiags(np.r_[-e, 2*e, -e], [-1,0,1],n,n).toarray()
x = spla.spsolve(A, np.transpose(e))

pyplot.plot(x)
pyplot.show()


二階微分を表す$K$によって演算した時、定数になるような解なので、解が二次曲線になっているのは妥当な感じがする。

### 1.1.23
長さ4のベクトル$u,v,w$を作り、$A=spdiags([u,v,w],-1,1,n,n)$と入力せよ。u,vの要素のうち、Aの-1,1番の対角線から省略されるものはどれか。

#### 解答
MATLABでないので少し違うが、



In [ ]:
u_4 = np.transpose(np.array([1,2,3,4]))
v_4 = np.array([5,6,7,8])
w_4 = np.array([9,10,11,12])
diag = np.array([0, -1, 1])
print(sp.spdiags([u_4,v_4,w_4], diag, 4, 4))



### 1.1.24

#### 解答


In [ ]:
A = sp.lil_matrix((1000, 1000))
A[0, :100] = 1
A[1, 100:200] = A[0, :100]
A.setdiag(-1)
print(A)

### 1.1.25


#### 解答
N＊N行列であるとして、detB, detCは０になる。従ってその行列のランクはN-1以下である。よって、対角優位論法では最後の行で0となるため、解が複数存在し、u=0のみにはならない。

### 1.1.26
toeplitz(v)が巡回行列となるようなvは？


#### 解答
vの第一要素から3要素目までと、N番目の要素が非0であるようなベクトル



In [ ]:
linalg.toeplitz([1,2,0,0,3])

### 1.1.27


#### 解答


In [ ]:
a = (np.array([[-1,-1,-1,-1]]))
b=(np.array([[1,1,1,1]]))
A = sp.spdiags(np.r_[a, b], [0,1],3,4).toarray()

#B
print(A)
print(np.transpose(A).dot(A))

#T
A_1 = A[0:4, 0:3]
print(A_1)
print(np.transpose(A_1).dot(A_1))

#K
A_2 =  A_1[0:3, 1:3]
print(A_2)
print(np.transpose(A_2).dot(A_2))