### 1.3.1


#### 解答



In [31]:

A = np.array([[2., -1., 0.],
              [-1., 2., -1.],
              [0., -1., 2.]])
detA = np.linalg.det(A)

P, L, U = lu(A)
L_t = L.T
D = np.diag([U[0][0], U[1][1], U[2][2]])
print("L: \n", L)
print("D: \n", D)
print("L^T: \n", L_t)
print("detA: \n", detA)

L: 
 [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.         -0.66666667  1.        ]]
D: 
 [[ 2.          0.          0.        ]
 [ 0.          1.5         0.        ]
 [ 0.          0.          1.33333333]]
L^T: 
 [[ 1.         -0.5         0.        ]
 [ 0.          1.         -0.66666667]
 [ 0.          0.          1.        ]]
detA: 
 4.0


### 1.3.2


#### 解答



In [32]:
inv_L = np.linalg.inv(L)
inv_D = np.linalg.inv(D)
inv_L_t = np.linalg.inv(L_t)
print("inv_L: \n", inv_L)
print("inv_D: \n", inv_D)
print("inv_L^T: \n", inv_L_t)

inv_L: 
 [[ 1.          0.          0.        ]
 [ 0.5         1.          0.        ]
 [ 0.33333333  0.66666667  1.        ]]
inv_D: 
 [[ 0.5         0.          0.        ]
 [ 0.          0.66666667  0.        ]
 [ 0.          0.          0.75      ]]
inv_L^T: 
 [[ 1.          0.5         0.33333333]
 [ 0.          1.          0.66666667]
 [ 0.          0.          1.        ]]


In [33]:
LL_inv = np.dot(L,inv_L)
print('LL^-1: \n', LL_inv)

LL^-1: 
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### 1.3.3


#### 解答



In [34]:
K5 = toeplitz([2,-1,0,0,0])
print('K5: \n', K5)

K5: 
 [[ 2 -1  0  0  0]
 [-1  2 -1  0  0]
 [ 0 -1  2 -1  0]
 [ 0  0 -1  2 -1]
 [ 0  0  0 -1  2]]


In [35]:
detK5 = np.linalg.det(K5)
inv_K5 = np.linalg.inv(K5)
print('det(K5): \n', detK5)
print('inv_K5: \n', inv_K5)
print('det(K5)*inv_K5: \n', np.dot(detK5,inv_K5))

det(K5): 
 6.0
inv_K5: 
 [[ 0.83333333  0.66666667  0.5         0.33333333  0.16666667]
 [ 0.66666667  1.33333333  1.          0.66666667  0.33333333]
 [ 0.5         1.          1.5         1.          0.5       ]
 [ 0.33333333  0.66666667  1.          1.33333333  0.66666667]
 [ 0.16666667  0.33333333  0.5         0.66666667  0.83333333]]
det(K5)*inv_K5: 
 [[ 5.  4.  3.  2.  1.]
 [ 4.  8.  6.  4.  2.]
 [ 3.  6.  9.  6.  3.]
 [ 2.  4.  6.  8.  4.]
 [ 1.  2.  3.  4.  5.]]


In [36]:
P, L_5, U_5 = lu(K5)
D_5 = np.diag([U_5[0][0], U_5[1][1], U_5[2][2], U_5[3][3], U_5[4][4]])
print("L_5: \n", L_5)
print("D_5: \n", D_5)
print("U_5: \n", U_5)

L_5: 
 [[ 1.          0.          0.          0.          0.        ]
 [-0.5         1.          0.          0.          0.        ]
 [ 0.         -0.66666667  1.          0.          0.        ]
 [ 0.          0.         -0.75        1.          0.        ]
 [ 0.          0.          0.         -0.8         1.        ]]
D_5: 
 [[ 2.          0.          0.          0.          0.        ]
 [ 0.          1.5         0.          0.          0.        ]
 [ 0.          0.          1.33333333  0.          0.        ]
 [ 0.          0.          0.          1.25        0.        ]
 [ 0.          0.          0.          0.          1.2       ]]
U_5: 
 [[ 2.         -1.          0.          0.          0.        ]
 [ 0.          1.5        -1.          0.          0.        ]
 [ 0.          0.          1.33333333 -1.          0.        ]
 [ 0.          0.          0.          1.25       -1.        ]
 [ 0.          0.          0.          0.          1.2       ]]


### 1.3.6


#### 解答
$5 + (5*5 - 5)/2 = 15$
