In [5]:
import numpy as np
import scipy 
import scipy.sparse as sp
from scipy.linalg import toeplitz
from scipy import integrate
import math
from matplotlib import pyplot as plt
from scipy import signal, interpolate
import scipy.linalg as linalg
from sympy import *
%pylab inline --no-import-all

ModuleNotFoundError: No module named 'matplotlib'

In [6]:
C4 = toeplitz([2,-1,0,0], [0,-1,0,0])
C4[3,0] = -1
C4[0,3] = -1 
C4
n = np.eye(4)
n[3,3] = -1
CC4 = np.dot(n,C4)
print(C4)
print(n)
print(CC4)

print(np.linalg.det(CC4))

[[ 2 -1  0 -1]
 [-1  2 -1  0]
 [ 0 -1  2 -1]
 [-1  0 -1  2]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]
[[ 2. -1.  0. -1.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 1.  0.  1. -2.]]
-8.881784197e-16


In [7]:
K4 = toeplitz([2,-1,0,0], [0,-1,0,0])
K5 = toeplitz([2,-1,0,0,0], [0,-1,0,0,0])
K6 = toeplitz([2,-1,0,0,0,0], [0,-1,0,0,0,0])


T4 = toeplitz([2,-1,0,0], [0,-1,0,0])
T4[0,0] = 1

C4 = toeplitz([2,-1,0,0], [0,-1,0,0])
C4[3,0] = -1
C4[0,3] = -1 
C4

B4 = toeplitz([2,-1,0,0], [0,-1,0,0])
B4[0,0]= 1
B4[3,3]= 1
B5 = toeplitz([2,-1,0,0,0], [0,-1,0,0,0])
B5[0,0]= 1
B5[4,4]= 1

## 問題1-4-1

$-u'' = δ（x-a）$の解は点荷重の両側で線形でなければならない.  
$u(0) = 2$ ,$u(1) = 4$ の場合、次の定数A,B,C,Dを決める４つの条件は何か？  
  
$u(x) = Ax + B$ ($0<x<a$のとき)  
and  
$u(x) = Cx + D$ ($a<x<1$のとき) 

### 解答
$u(x) = -1x + 2$ ($0<x<a$のとき)  
$u(x) = -2x + 2$ ($a<x<1$のとき) 

In [1]:
#1-4-1

print('u(x) = Ax + B (0<x<a) ')
print('u(x) = Cx + D (a<x<1) ')

print('A,B,C,Dを決める４つの条件')
print('u(0) = B = 2')#固定端での条件
print('u(1) = C + D = 0')#固定端での条件
print('u(a) = Aa + B = Ca + D')#aの点であるという条件
print('A = C + 1')#傾きが−１される条件

u(x) = Ax + B (0<x<a) 
u(x) = Cx + D (a<x<1) 
A,B,C,Dを決める４つの条件
u(0) = B = 2
u(1) = C + D = 0
u(a) = Aa + B = Ca + D
A = C + 1


## 問題1-4-2

問題１を自由端-固定端　$u'(0) = 0 , u(1) = 4$の場合に変更せよ。  
A,B,C,Dを決める４つの方程式を見つけてとけ。

### 解答
$u(x) =  5$ ($0<x<a$のとき)  
$u(x) = -x + 5+a$ ($a<x<1$のとき) 

In [2]:
print('u(x) = Ax + B (0<x<a) ')
print('u(x) = Cx + D (a<x<1) ')

print('A,B,C,Dを決める４つの条件')
print('u’(0) = A = 0')#自由端での条件
print('u(1) = C + D = 4')#固定端での条件
print('u(a) = Aa + B = Ca + D')#aの点であるという条件
print('A = C + 1')#傾きが−１される条件
print('A = 0,B = -a + 5,C = -1,D = 5')

u(x) = Ax + B (0<x<a) 
u(x) = Cx + D (a<x<1) 
A,B,C,Dを決める４つの条件
u’(0) = A = 0
u(1) = C + D = 4
u(a) = Aa + B = Ca + D
A = C + 1
A = 0,B = -a + 5,C = -1,D = 5


## 問題1-4-3

点$a = 1/3 とb = 2/3 $に二つの点荷重があるとするとき、このとき、固定端-固定端の問題を２つの方法で解け。  
第１の方法では、それぞれの点荷重に対する２うの解を組み合わせよ。  
第2の方法では,次のA,B,C,D,E,Fに対する６個の条件を見つけよ。  
  
$u(x) = Ax + B (0<x<1/3のとき)$  
$u(x) = Cx + D (1/3<x<2/3のとき)$  
$u(x) = Ex + F (2/3<x<1のとき)$

### 解答
$u(x) = x  　(0<x<1/3のとき)$  
$u(x) = 1/3 　(1/3<x<2/3のとき)$  
$u(x) = -x + 1 　(2/3<x<1のとき)$

In [8]:
inv_K5 = np.linalg.inv(K5)
f = np.array([0,1,0,1,0])
u = np.dot(inv_K5,f)
# print(u)
# print(6*inv_K5)

f1 = np.array([0,1,0,0,0])
u1 = np.dot(inv_K5,f1)
print(u1)

f2 = np.array([0,0,0,1,0])
u2 = np.dot(inv_K5,f2)
print(u2)

U = (u1 + u2)/6
U = np.append(U,[0])
U = np.insert(U,0,0)
print(U)
plt.plot(U)

[ 0.66666667  1.33333333  1.          0.66666667  0.33333333]
[ 0.33333333  0.66666667  1.          1.33333333  0.66666667]
[ 0.          0.16666667  0.33333333  0.33333333  0.33333333  0.16666667
  0.        ]


NameError: name 'plt' is not defined

In [9]:
#1-4-3
print('u(x) = Ax + B (0<x<1/3) ')
print('u(x) = Cx + D (1/3<x<2/3) ')
print('u(x) = Ex + F (2/3<x<1) ')
print('両方の固定端を０とする')
print('A,B,C,D,E,Fを決める6つの条件')
print('u(0) = B = 0')#固定端での条件
print('u(1) = E + F = 0')#固定端での条件
print('u(1/3) = 1/3*A + B = 1/3*C + D')#1/3の点で連続あるという条件
print('A = C + 1')#傾きが−１される条件
print('u(2/3) = 2/3*C + D = 2/3*E + F')#2/3の点で連続あるという条件
print('C = E + 1')#傾きが−１される条件


u(x) = Ax + B (0<x<1/3) 
u(x) = Cx + D (1/3<x<2/3) 
u(x) = Ex + F (2/3<x<1) 
両方の固定端を０とする
A,B,C,D,E,Fを決める6つの条件
u(0) = B = 0
u(1) = E + F = 0
u(1/3) = 1/3*A + B = 1/3*C + D
A = C + 1
u(2/3) = 2/3*C + D = 2/3*E + F
C = E + 1


## 問題1-4-4

方程式を固定端-自由端の境界条件u(0) = 0, n'(1) = 0 の元で解け  
u(x)とu'(x)のグラフを描け

### 解答
$u(x) = x  $ ($0<x<a$のとき)  
$u(x) = a $ ($a<x<1$のとき) 

In [3]:
# 1-4-4
print('u(x) = Ax + B (0<x<a) ')
print('u(x) = Cx + D (a<x<1) ')

print('A,B,C,Dを決める４つの条件')
print('u(0) = B = 0')#固定端での条件
print('u’(1) = C = 0')#自由端での条件
print('u(a) = Aa + B = Ca + D')#aの点であるという条件
print('A = C + 1')#傾きが−１される条件


T5 = toeplitz([2,-1,0,0,0], [0,-1,0,0,0])
T5[4,4] = 1
inv_T5 = np.linalg.inv(T5)
f_4 = np.array([0,1,0,0,0])
U_4= np.dot(inv_T5,f_4)
U_4 = np.insert(U_4,0,0)
U_4 = np.append(U_4,[2])
U_4 = U_4/6
print(U_4)
plt.plot(U_4)

u(x) = Ax + B (0<x<a) 
u(x) = Cx + D (a<x<1) 
A,B,C,Dを決める４つの条件
u(0) = B = 0
u’(1) = C = 0
u(a) = Aa + B = Ca + D
A = C + 1


NameError: name 'toeplitz' is not defined

## 問題1-4-5

同じ自由端-固定端の条件$u'(0) = 0, n'(1) = 0$ の条件を課すと、解が存在しないことを示せ。  
CとDに対する連立方程式は解を持たない。これは得意な行列Bに対応する

In [10]:
#1-4-5
print('u(x) = Ax + B (0<x<a) ')
print('u(x) = Cx + D (a<x<1) ')

print('A,B,C,Dを決める４つの条件')
print('u’(0) = B = 0')#固定端での条件
print('u’(1) = D = 0')#自由端での条件
print('u(a) = Aa + B = Ca + D')#aの点であるという条件
print('A = C + 1')#傾きが−１される条件


print(B4)
print(np.linalg.det(B4))

u(x) = Ax + B (0<x<a) 
u(x) = Cx + D (a<x<1) 
A,B,C,Dを決める４つの条件
u’(0) = B = 0
u’(1) = D = 0
u(a) = Aa + B = Ca + D
A = C + 1
[[ 1 -1  0  0]
 [-1  2 -1  0]
 [ 0 -1  2 -1]
 [ 0  0 -1  1]]
0.0


## 問題1-4-6


$-u'' = δ（x-a）$は周期的境界条件$u(0) = u(1),u'(0) = u'(1)$の下では解を持たないことを示せ.  
これは特異な巡回行列Cに対応する。

In [11]:
#1-4-6
print(C4)
print(np.linalg.det(C4))
print('巡回行列は特異な行列なので解を持たない')

[[ 2 -1  0 -1]
 [-1  2 -1  0]
 [ 0 -1  2 -1]
 [-1  0 -1  2]]
8.881784197e-16
巡回行列は特異な行列なので解を持たない


##  問題1-4-7

点荷重を変えて$f(x)=δ(x-1/3)-δ(x-2/3)$とすると、$-u'' = f(x)$は自由端-固定端の境界条件の元でも解をもつことを示せ。  
$u'(0)=0,u'(1)=0$として無限に多くの解を求めよ


### 解答

方程式を解くと$A=0,E=0$  
$A=C+1,E=C+１$→$C=-1$  
$B  = a+ D$  
$F = b+ D$

Dの値を決めることでBとFの値が決まる。  
そしてDの値は任意の値を代入できるので、それぞれの任意のDに対応したB、Fの解が存在する。  
なので解は無限に存在する。

In [12]:
#1-4-7

print('u(x) = Ax + B (0<x<1/3) ')
print('u(x) = Cx + D (1/3<x<2/3) ')
print('u(x) = Ex + F (2/3<x<1) ')
print('両方の固定端を０とする')
print('A,B,C,D,E,Fを決める6つの条件')
print('u’(0) = A = 0')#固定端での条件
print('u’(１) = E = 0')#固定端での条件
print('u(a) = a*A + B = a*C + D')#1/3の点で連続あるという条件
print('A = C + 1')#傾きが−１される条件
print('u(b) = b*C + D = b*E + F')#2/3の点で連続あるという条件
print('C = E - 1')#傾きが−１される条件


u(x) = Ax + B (0<x<1/3) 
u(x) = Cx + D (1/3<x<2/3) 
u(x) = Ex + F (2/3<x<1) 
両方の固定端を０とする
A,B,C,D,E,Fを決める6つの条件
u’(0) = A = 0
u’(１) = E = 0
u(a) = a*A + B = a*C + D
A = C + 1
u(b) = b*C + D = b*E + F
C = E - 1


In [ ]:
#1-4-7

print('u(x) = Ax + B (0<x<a) ')
print('u(x) = Cx + D (a<x<1) ')

print('A,B,C,Dを決める４つの条件')
print('u’(0) = A = 0')#固定端での条件
print('u’(1) = C  = 0')#固定端での条件
print('u(a) = Aa + B = Ca + D')#aの点であるという条件
print('A = C + 1')#傾きが−１される条件



#それぞれを計算しても解がもとまらない
a = 1/3
A,B,C,D = symbols('A B C D')
eq1 = A
eq2 =  C 
eq3 = A*a + B - C*a  -D
eq4 = A - C - 1
solve([eq1,eq2,eq3,eq4],[A,B,C,D])

b = 2/3
A2,B2,C2,D2 = symbols('A2 B2 C2 D2')
eq5 = A2
eq6 =  C2
eq7 = A2*b + B2 - C2*b  -D2
eq8 = A2 - C2 - 1
solve([eq5,eq6,eq7,eq8],[A2,B2,C2,D2])


## 問題1-4-8

差によって定義される点荷重$f(x)=δ(x-1/3)-δ(x-2/3)$は荷重の合計がゼロであり、$-u''=f(x)$は周期的境界条件の素でも解くことができる。まず特殊解を見つけ次に特殊解＋零空間解を求めよ


### 解答
点荷重が$f(x)=δ(x-1/3)-δ(x-2/3)$であることから$-u''=f(x)$は$R(x-a)$を傾斜関数として  
特殊解は$R(x-1/3)＋R(x-2/3)$となる  
零空間解を$Cx＋D$とすると  
u(x)=$R(x-1/3)-R(x-2/3)+Cx+D$となる。
固定端、自由端それぞれの条件を  
u(0) = a  
u(1) = b  
u'(0) = a'  
u'(1) = b'とする。  
  
  
u(0) = D = a  
u(1) = 1/3+C+D=b  
u'(0)= C = a'  
u'(1) = 1 + C = b'

固定端-固定端  
$C = b-a+1/3$  
$D = a$  
自由端-固定端  
$c = a'$  
$D = b-a'+1/3$  
固定端-自由端  
$C = b'-1$  
$D = a$  
自由端-自由端  
$a'-b'=1$を満たす任意のCとD



## 問題1-4-9

分布荷重＄f(x) = 1＄は荷重$δ(x-a)$の全ての点＄x=a＄にあたる積分である。したがって、第1.3節での自由端-固定端の解$u(x) = 1/2(1-x^2)$は点荷重に対する解  
($a<x$のとき$1-x,a>x$のとき$1-a$)の積分となっているはずである)

$u(x)=\int_{0}^{x}(1-x)da$+$\int_{x}^{1}(1-a)da$= $1/2 - 1/2x^2$
固定端-固定端の場合を確かめよ

### 解答
$u(x)=\int_{0}^{x}(1-x)ada$+$\int_{x}^{1}(1-a)xda= -1/2x^2+1/2x$
となり１.2節の例と一致した


## 問題 1-4-10


$K^-1$の列を全て足すと、方程式$Ku = f$の解である離散版の放物線が得られる。このときfはどんなベクトルか？  
図1.9の$K^-1$および図1.10の$T^-1$に対してこの足し算を実行せよ

### 解答
fは全要素が１であるようなベクトルである。


In [ ]:
n=15
K_n  =toeplitz([2, -1]+[0]*(n-2))
T_n = toeplitz([2, -1]+[0]*(n-2))
T_n[0,0]=1
inv_K_n = np.linalg.inv(K_n)
inv_T_n = np.linalg.inv(T_n)
sumK_n = np.sum(inv_K_n, axis=0)
sumT_n = np.sum(inv_T_n, axis=0)
print(sumK_n)
print(sumT_n)
plt.plot(sumK_n)
plt.plot(sumT_n)

# f = np.array([0,0,0,0,1,0,0,0,0,0,0,0,0,0,0])
# uK = np.dot(inv_K_n,f)
# print(uK)
# plt.plot(uK)
# uT = np.dot(inv_T_n,f)
# print(uT)
# plt.plot(uT)



## 問題1-4-11

$δ（x）$の積分は段階関数である$S（x）$である。$S（x）$の積分は傾斜関数$R（x）$である。次の２つの積分のグラフを描け。二次スプライン$Q（x）$及び三次スプライン$C（x）$.点$x＝０$においては$C（x）$の何次までの微分連続か？

### 解答
C（x）でのx＝０の点では３次まで微分可能である。

n次スプライン補間が満たす条件
関数f（x）の３次スプライン補間S（x）を考える  

$j = 0,1,2,・・・・n-2$において  
  
１,$S(x_{j}) = f(x_{j})$  
2,$S_{j+1}(x_{j+1}) = S_{j}(x_{j+1})$  
3,$S_{j+1}'(x_{j+1}) = S_{j}'(x_{j+1})$  
4,$S_{j+1}''(x_{j+1}) = S_{j}''(x_{j+1})$    
  
n+1,$S_{j+1}^{(n-1)}(x_{j+1}) = S_{j}^{(n-1)}(x_{j+1})$


## 問題1-4-12

三次スプライン$C(x)$は4階微分方程式$u''''=δ（x）$の解である.4個の任意定数をもつ完全解$u(x)$は何か？$u(1)=u''(1)=u(-1)=u''(-1)=0$が成り立つようなこれらの定数を定めよ.  
これは点荷重の下で一様な単純支持梁のたわみを与える。

### 解答

$u(x)= a + bx + c/2x^2 + d/6x^3$  
$u(1)=u''(1)=u(-1)=u''(-1)=0$より  
$u(1) = a+b+c/2+d/6=0$  
$u(-1) = a-b+c/2-d/6=0$  
$u''(1) = d+c=0$  
$u''(ー1) = d-c=0$  
  
以上より　　


## 問題1-4-13

デルタ関数$δ(x)$の特徴付けは次のとうりである。  
任意のなめらかな関数g(x)に対して$\int_{-∞}^{∞}δ(x)g(x)dx = g(0)$  
これから,δ(x)の下の"面積が１"ということはどうやって導けるのか？  
また$\int δ(x-3)g(x)dx$はどうなるか？

### 解答
1,g(x)=1を上記の定義式に代入すると
$\int_{-∞}^{∞}δ(x)dx = g(0)　= 1$となる

2,$\int δ(x-3)g(x)dx=g(3)$

## 問題1-4-14

関数δ(x)は、次のような極めて背が高い方波形SWの”弱極限”である。  
$SW(x) = \frac{1}{2h}||x|<h)$とすると$\int SW(x)g(x)dx→g(0) , (h→0)$  
定数g(x) = 1および全ての$g(x) = x^n$に対して、$\int SW(x)g(x)dx→g(0)$を示せ  
ここで上記の規則は試験関数g(x)に依存するから"弱"という言葉を使った

### 解答
|x|<hの条件を使ってh→０の極限で積分解けばできます

## 問題1-4-15

δ(x)の微分はダブレットδ’（x）である.部分積分を用いて次の式を完成させよ.  
なめらかなg(x)に対して$\int^{∞}_{-∞} g(x)δ’（x）dx=\int^{∞}_{-∞} (?)δ（x）dx = ?$


### 解答
部分積分を用いて  
$\int^{∞}_{-∞} g(x)δ’（x）dx = [g(x)δ(x)]^{∞}_{-∞}-\int ^{∞}_{-∞}g'(x)δ(x)dx = -g'(0) $

ダブレットδ'(x)任意の関数g(x)とともに積分するとx =0の微分値にマイナスをかけたものが出てくる

## 問題1-4-16

-u''-u = 0をu(0)=0としてx＝０から出発して解け.この時,任意定数Aが残る。  
次に、この解においてxを1-xで置き換えることにより、u(1)=0を満たす-u''-u=0の解を求めよ
この任意定数をBとする、点荷重をδ（x-1/2）として点x = 1/2での"ジャンプの条件"よりAとBを求めよ。  
h=1/4,f=(0,4,0)として、差分方程式Ku=fを作って解け

### 解答
$-u''-u=0$より  
$u(x) = -R(x)+Ax+B$  
$u(0)=-R(0)+B=0,u(x) = -R(x)+Ax$  
$u(1-x) = -R(1-x)+A(1-x)+B$
$u(1)=-1+A+B=0,u(1-x) = -R(1-x)+(B-1)x+1$  
$u(1/2)=-R(1/2)+1/2A=-R(1/2)+1/2(B-1) +1,A = B+1$  
$u'(1/2)=-S(1/2)+A=-S(1/2)+(B-1),A=B-1$  