In [2]:
import numpy as np
import scipy 
import scipy.sparse as sp
from scipy.linalg import toeplitz
from sympy import *
from scipy import integrate
import math
from matplotlib import pyplot as plt
from scipy import signal, interpolate
import scipy.linalg as linalg
import scipy.sparse as sp
import scipy.sparse.linalg as spla
%pylab inline --no-import-all

ModuleNotFoundError: No module named 'sympy'

In [3]:
import numpy as np
import scipy 
import scipy.sparse as sp
from scipy.linalg import toeplitz
from scipy import integrate
import math
from scipy import signal, interpolate
import scipy.linalg as linalg
import scipy.sparse as sp
import scipy.sparse.linalg as spla


## 問題2-2-1

$u''+u=0$に対する蛙跳び法の行列$G_L=\begin{bmatrix}1 & h \\-h & 1-h^2 \end{bmatrix}$の固有値を$λ_1,λ_2$とする  
(a)トレース$λ_1+λ_2=e^{iθ}+e^{-iθ}$より$h<2$に対して$cosθ=1-\frac{1}{2}h^2$であることを見出せ  
(b)h=2において、$G_L$の固有値と全ての固有ベクトルを求めよ  
(c)h=3において、固有値を求め$λ_1λ_2=1$であるが$|λ_{max}|>1$であることを示せ

### 解答
(a)$λ_1+λ_2=e^{iθ}+e^{-iθ}$より  
$e^{iθ}+e^{-iθ}=2-h^2$  
$e^{iθ}=cosθ＋isinθ$より$e^{iθ}+e^{-iθ}=2cosθ=2-h^2$  
以上より$cosθ=1-\frac{1}{2}h^2$  
 

In [17]:
h = 2
Gb = np.array([[1,h],[-h,1-h*h]])
l1, S1 = np.linalg.eig(Gb)
print("(b)")
print(Gb)
print(l1)
print(S1)



(b)
[[ 1  2]
 [-2 -3]]
[-1. -1.]
[[ 0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [18]:
h = 3
Gc = np.array([[1,h],[-h,1-h*h]])
l1, S1 = np.linalg.eig(Gc)
print("(c)")
print(Gc)
print(l1)
print(S1)


(c)
[[ 1  3]
 [-3 -8]]
[-0.14589803 -6.85410197]
[[ 0.93417236 -0.35682209]
 [-0.35682209  0.93417236]]


## 問題 2-2-2

問題１で、半角公式より$cosθ=1-\frac{1}{2}h^2$から$h=2sin(θ/2)$が成り立つ。すると$θ=2π/N$と$h=2sin(θ/N)$より$cosNθ=cos2π=1$が導かれる。この特別な場合には、$(U_N,V_N)$は$(U_0,V_0)$に戻り$G^N=1$である。  
N=3と４に対してN個の点$(U_N,V_N)=G^N(1,0)$をプロットせよ。  
$(0,0)$から$(U_N,V_N),(U_{N+1},V_{N+1})$をつないだ３ないし４個の三角形の等積性をチェックせよ。


In [9]:
N = 3
a = np.array([1,0])
h = 2*np.sin(np.pi/N)
Gc3 = np.array([[1,h],[-h,1-h*h]])
l3, S3 = np.linalg.eig(Gc3)
G31=Gc3
G32=np.dot(Gc3,Gc3)
G33=np.dot(np.dot(Gc3,Gc3),Gc3)

print(np.dot(G31,a))
print(np.dot(G32,a))
print(np.dot(G33,a))

N = 4
h = 2*np.sin(np.pi/N)
Gc4 = np.array([[1,h],[-h,1-h*h]])
l4, S4 = np.linalg.eig(Gc4)
G41=Gc4
G42=np.dot(Gc4,Gc4)
G43=np.dot(np.dot(Gc4,Gc4),Gc4)
G44=np.dot(np.dot(Gc4,Gc4),np.dot(Gc4,Gc4))
# print(G44)

print(np.dot(G41,a))
print(np.dot(G42,a))
print(np.dot(G43,a))
print(np.dot(G44,a))

[ 1.         -1.73205081]
[-2.          1.73205081]
[  1.00000000e+00   1.33226763e-15]
[ 1.         -1.41421356]
[ -1.00000000e+00  -6.66133815e-16]
[-1.          1.41421356]
[  1.00000000e+00   1.33226763e-15]


## 問題2-2-3

(大難問)図2.7の内側の
楕円の各軸は何だろうか？

## 問題2-2-4

図2.6の蛙跳び法のなす楕円は、$G^T_LG_L$の固有値の平方根である$σ_1とσ_2$を半軸とする。この行列の行列式は１であり（したがって$σ_1σ_2=1$),
トレースは$2+h^4$(固有値の和である$σ_1^2+σ_2^2$)であることを示せ。  
  
円に近い楕円　$(σ_1^2-σ_2^2)=σ_1^2+σ_2^2-2=h^4$  
$σ_{max}-σ_{min}=h^2$


### 解答
$G_L=\begin{bmatrix}1 & h \\-h & 1-h^2 \end{bmatrix}$
$G^T_L=\begin{bmatrix}1 & -h \\h & 1-h^2 \end{bmatrix}$  
$G^T_LG_L=\begin{bmatrix}1+h^2 & -h^3 \\-h^3 & h^4-h^2+1 \end{bmatrix}$

以上より$det(G^T_LG_L)=1,trace(G^T_LG_L)=2+h^4$

## 問題2-2-5

この問題の行列では次のよう歪対称$(A^T=-A)$である。  
$\frac{du}{dt}=\begin{bmatrix}0 & c & -b \\-c & 0 & a\\b & -a & 0 \end{bmatrix}$あるいは  
$u'_1=cu_2-bu_3$  
$u'_2=au_3-cu_1$  
$u'_3=bu_1-au_2$  
(a)$||u(t)||^2=u_1^2+u_2^2+u_3^2$の導関数は、$2u_1u'_1+2u_2u'_2+2u_3u'_3$である。ここに$u'_1u'_2u'_3$を代入して導関数=ゼロを確認せよ。したがって$||u(t)||^2=||u(0)||^2$である  
  
(b)行列用語でいうと$Q=e^{At}$は直交である。級数$Q=e^{At}=I+At+(At)^2/2t+,,,,,$より、$Q^T=e^{-At}$を示せ。すると確かに$Q^TQ=I$である。

###  解答
(a)
$u'_1=cu_2-bu_3$  
$u'_2=au_3-cu_1$  
$u'_3=bu_1-au_2$  
より$2u_1(cu_2-bu_3)+2u_2(au_3-cu_1)+2u_3(bu_1-au_2)=0$

(b)
$Q=e^{At}=I+At+(At)^2/2t+,,,,,$
$Q^T=I^T+A^Tt+(A^Tt)^2/2t+,,,,,=e^{-A^T}=I+-A^T+(-A^T)^2/2t+,,,,,=e^{-At}$


## 問題2-2-6

台形則は,$u'=Au$で$A^T=-A$の時、エネルギー$||u||^2$を保存する。(24)に$U_{n+1}+U_n$を乗じ、$||U_{n+1}||^2=||U_n||^2$を示せ。増大度行列$G_T=(I-AΔt/2)^{-1}(I+AΔt/2)$は$A^T=-A$ならば$e^{At}$と同様に直交である。  
u'=Auは$||u||^2$を保存  
$\frac{d}{dt}(u,u')=(u',u)+(u,u')=((A+A^TΔt/2)u,u)=0$

###  解答
$(I-\frac{Δt}{２}A)U_{n+1}=(I+\frac{Δt}{２}A)U_{n}$ (24)  
この両辺に$U_{n+1}+U_n$を乗じると
$(I-\frac{Δt}{２}A)U_{n+1}（U_{n+1}^T+U_n^T）=(I+\frac{Δt}{２}A)U_{n}(U_{n+1}^T+U_n^T)$ 
行列Aの性質から$(I-\frac{Δt}{２}A)=(I+\frac{Δt}{２}A)$なので$||U_{n+1}||^2=||U_n||^2$

## 問題2-2-7

台形則にはエネルギー誤差はないが小さな位相誤差がある。$h=2π/32$で３２ステップ進んでも完璧な１に至らない、$λ=(1+i\frac{h}{2})/(1-i\frac{h}{2})$の時、$λ^{32}$とその偏角$θ$を計算せよ。
$λ$を$e^{ih}$と比べてhのどのべきん乗で違いが生じているか？

In [9]:
h = (2*np.pi)/32
l = (1+h*0.5j)/(1-h*0.5j)
l32 = np.power(l,32)
l32

tan = np.imag(l32)/np.real(l32)
theta = np.arctan(tan)
print(l32)
print(theta )

l2 = np.exp(h*1j)
l32_2 = np.power(l2,32)

tan2 = np.imag(l32_2)/np.real(l32_2)
theta2 = np.arctan(tan2)
print(l32_2)
print(theta2)

print(h*h*h)

(0.99979859551-0.0200690910568j)
-0.0200704385004
(1+0j)
0.0
0.007569891767651322


## 問題2-2-8

前進オイラー方では次のように毎ステップごとでエネルギー$1+h^2$が
乗ざれる。  
エネルギー　$U^2_{n+1}+V^2_{n+1}=(U_n+hV^2_n)^2+U_n-hV^2_n)^2=(1+h^2)(U^2_n+V^2_n)$  
$h=2π/32$に対して$(1+h^2)^{32}$を計算せよ。h→０の時$(1+h^{32})^{\frac{2π}{h}}$は１に近くだろうか？そうでないだろうか？  
もしそうならオイラー法はゆっくり収束する。交代オイラー法の各ステップではエネルギー$U^2_n+V^2_n$を$1+h^2$で叙すことを示せ

In [10]:
h = (2*np.pi)/32
a = np.power((1+h*h),32)
print(a)

3.35520584402


後退オイラー方法
$U_{n+1}=U_n+hV_{n+1}$  
$V_{n+1}=V_n+hU_{n+1}$  
以上から$U^2_{n+1}+V^2_{n+1}=h^2U^2_{n+1}+h^2V^2_{n+1}+U^2_n+V^2_n+2h(U_nV_{n+1}-V_nU_{n+1})$  
よって$(1-h^2)(U^2_{n+1}+V^2_{n+1})=U^2_n+V^2_n$

## 問題2-2-9

ニュートン法の収束における$"ma"$は実は３段階$\frac{d}{dt}(m(u,t),\frac{du}{dt})$を意味する。質量が一定の時これは$"mu"$である。しかしアインシュタインは、質賞は速度とともに増加することを見出した。低速度の例として屋根のない列車に雨が$r=dm/dt$の比率で落ちてくると考えよう。列車を一定速度vに保つには、どのような力Fが必要だろうか？（ここではma=0だがF=0ではない）

列車の質量をMとすると
$m=M＋rt$
$\frac{d(mv)}{dt}=F$  
$\frac{d((M+rt)v)}{dt}=F$となりvが一定となるような力Fは$F=rv$である

## 問題2-2-10

式(16)において、共振は近接共振公式の$ω_0$が$λ$に近づいた極限であることを示せ。結局のところ $f/g$ が $0/0$ に近づくときの極限として $f'/g'$ になるというロピタルの規則が必要になろう

近接共振$u(t)=\frac{cosλtーcosω_0t}{m(ω_0^2-λ^2)}$（１）  
共振$u(t)=\frac{tsinω_0t}{2mω_0}$（２）  

$a=λ-ω_0$として（１）に代入すると$u(t)=\frac{cos(a+ω_0)tーcosω_0t}{m(ω_0^2-(a+ω_0)^2)}$
ここで$λ→ω_0$より$a→0$
ロピタルの定理よりu(t)の分子分母をaで微分すると  
$U(a)=\frac{-tsin(a+ω_0)t}{-2m(a+ω_0))}$  
$lim_{a→０}U(a)=\frac{tsinω_0t}{2mω_0}$となる


## 問題2-2-11

振動する線形ばね・質点系では、"ハミルトニアン"は全エネルギー$H=\frac{1}{2}p^TM^{-1}p+\frac{1}{2}u^TKu$である。位置uと運動量pはハミルトンの好みの未知量である。  
ハミルトン方程式$p'=-\frac{\partial H}{\partial u}$及び$u'=\frac{\partial H}{\partial p}$からニュートンの法則$Mu''+Ku=0$を導け

$H=\frac{1}{2M}p^2+\frac{1}{2}Ku^2$  
$p'=-\frac{\partial H}{\partial u}=-Ku$  
$u'=\frac{\partial H}{\partial p}=\frac{p}{M}$
以上より$Mu''+Ku=0$

## 問題 2-2-12

次の公式を使って、H（p,u）=一定はハミルトン方程式の第一積分であることを示せ。  
チェイン側  $\frac{dH}{dt}=\frac{\partial H}{\partial p}\frac{dp}{dt}+\frac{\partial H}{\partial u}\frac{du}{dt}=()+()=0$  
これまでたくさんの研究者が完全解を作るため第二積分を望んできた。互いに引き合う３体系でこれは不可能なことがわかった。冥王星の軌道はカオス的なのである。

### 解答
ハミルトン方程式$p'=-\frac{\partial H}{\partial p}$及び$u'=\frac{\partial H}{\partial p}$から  
$\frac{dH}{dt}=\frac{\partial H}{\partial p}\frac{dp}{dt}+\frac{\partial H}{\partial u}\frac{du}{dt}=(\frac{du}{dt}\frac{dp}{dt})+(-\frac{dp}{dt}\frac{du}{dt})=0$  


## 問題2-2-13

太陽と１惑星の系では、重力の法則により$H=\frac{1}{2}p^2_1+\frac{1}{2}p^2_2-(u^2_1+u^2_2)^{-\frac{1}{2}}$である。$p'_i=\frac{\partial H}{\partial u_i}$と$u'_i=\frac{\partial H}{\partial p_i}$よりu-p平面において面積$A(t)=u_1p_2-u_2p_1$は$\frac{dA}{dt}=0$を満たすことを示せ。  
これはケプラーの第二法則である。すなわち太陽から惑星までの線分は一定速度で面積を掃過する。ニュートンはこの法則を幾何学的に証明することで1687年にヴェレル法を発見した。

### 解答

$A(t)=u_1p_2-u_2p_1=\frac{\partial H}{\partial p_1}\frac{\partial H}{\partial u_2}-\frac{\partial H}{\partial p_2}\frac{\partial H}{\partial u_1}$

$\frac{dA}{dt}=\frac{\partial A}{\partial p_1}\frac{dp_1}{dt}+\frac{\partial A}{\partial u_1}\frac{du_1}{dt}+\frac{\partial A}{\partial p_2}\frac{dp_2}{dt}+\frac{\partial A}{\partial u_2}\frac{du_2}{dt}$  

$\frac{du_1}{dt}=\frac{\partial H}{\partial p_1}=p_1$  
$\frac{du_2}{dt}=\frac{\partial H}{\partial p_2}=p_2$  
$\frac{dP_1}{dt}=\frac{\partial H}{\partial u_1}=-\frac{u_1}{(u^2_1+u^2_2)^{\frac{3}{2}}}$  
$\frac{dP_2}{dt}=\frac{\partial H}{\partial u_2}=-\frac{u_2}{(u^2_1+u^2_2)^{\frac{3}{2}}}$  
$\frac{\partial A}{\partial p_1}=-u_2$  
$\frac{\partial A}{\partial p_2}=u_1$  
$\frac{\partial A}{\partial u_1}=p_2$  
$\frac{\partial A}{\partial u_2}=-p_1$  

## 問題 2-2-14

ロトカ-ヴォルテラ法では$alogu+blogv-u-v$は一定である。$p=logu$及び$q=logv$とおけばこの定数は$H=ap+bq-e^p-e^q$である。このハミルトニアンの$p'=-\frac{\partial H}{\partial q}$及び$q'=\frac{\partial H}{\partial p}$はまさにロトカ-ヴォルテラ方程式であることを示せ。被食者、捕食者では対数尺度で面積保存が成り立っている。

$H=ap+bq-e^p-e^q$  
$p'=-\frac{\partial H}{\partial q}$及び$q'=\frac{\partial H}{\partial p}$より  
$p'=b-e^q,q'=a-e^a$
$p=logu$及び$q=logv$より  
$p'=u'/u=b-v,q'=v'/v=a-u$  
以上より$u'=u(b-v),v'=v(a-u)$

## 問題 2-2-15

線形のステップ$U_{n+1}=aU_n+bV_n=cU_n+dV_n$は＿＿＿＝１の時（40）によってシンプレクティックである。行列式１である行列Gは何か？その時次式によって三角形の面積は等しく保たれる。$det\begin{bmatrix}U_{n+1} & U_{n+2} \\V_{n+1} & V_{n+2} \end{bmatrix}=(detG)det\begin{bmatrix}U_{n} & U_{n+1} \\V_{n} & V_{n+1} \end{bmatrix}$


## 問題2-2-16

次に与えられる非線形の蛙跳び法も$\frac{\partial G}{\partial U}\frac{\partial H}{\partial V}-\frac{\partial G}{\partial V}\frac{\partial H}{\partial U}=1$を満たすことを示せ。  
$U_{n+1}=G(U_n,V_n)=U_n+hV_n$  
$V_{n+1}=H(U_n,V_n)=V_n+hF(U_{n+1})=V_n+hF(U_n+hV_n)$

## 問題 2-2-17

単独方程式$mu''+cu=0$に対して蛙跳び法の$U_{n+1}$と$V_{n+1}$を書き下せ。増大行列Gとその固有値の和（トレース$G_{11}+G_{22}$）を見出せ。トレース>-2に対して$(Δt)^2<4m/c$が安定性の条件であることを示せ。


$\frac{U_{n+1}-U_n}{Δt}　= V_n$  
$\frac{V_{n+1}-Vn}{Δt}　= -\frac{c}{m}U_{n+1}$  
以上より  
$G=\begin{bmatrix}1 & Δt\\-\frac{c}{m}Δt & 1-\frac{c}{m}Δt^2 \end{bmatrix}$  
$trace(G)=2-\frac{c}{m}Δt^2 $  
$2-\frac{c}{m}Δt^2>-2$,$Δt^2<4\frac{m}{c}$


## 問題 2-2-18

差$cos9t-cos11$のグラフを書け。ゆっくり変動する$2sint$の鞘の内側に、遠い振動を観測するに違いない。この差は2sint10tsintに等しいからである。

In [ ]:
import matplotlib.pylab as plt
 

x = np.linspace(-np.pi,np.pi, 100)
a=np.cos(9*x)-np.cos(11*x)

plt.plot(x, 2*np.sin(x))
plt.plot(x,a)