In [2]:
import numpy as np
import scipy.linalg as linalg
from matplotlib import pyplot
import scipy.sparse as sp
import scipy.sparse.linalg as spla
import math

<hr>
## 2.1.1
$K^{-1}$に対する公式は、$K$の行列による乗算を含んでいる。両固定の場合の$K$は、

$K=\begin{bmatrix}c_1+c_2&-c_2&0\\ -c_2&c_2+c_3&-c_3\\ 0&-c_3&c_3+c_4\end{bmatrix}$

と与えられ(式7)、この行列式は

$\begin{align}det K &= (c_1+c_2)(c_2+c_3)(c_3+c_4)-c_2^2(c_1+c_2)-c_3^2(c_1+c_2)\\&= c_1c_2c_3+c_1c_3c_4+c_1c_2c_4+c_2c_3c_4\end{align}$

と計算される。半固定(式8)と無固定(式11)のときの行列式はどうなるか？

### 解答
・半固定：問題文にもある通り、4つ目のばねがないので$c_4=0$とおけばよく、$det\:K =  c_1c_2c_3$  
・無固定：1つ目のばねもないので、上記半固定にさらに$c_1=0$となり、$det\:K = 0$  
<hr>

<hr>
## 2.1.2
$K^{-1}$の各成分の分子($\frac{1}{det\:K}$以外の部分)は、その2×2小行列式から計算することができる（これらの小行列は$K$の余因子と呼ばれる）。例えば$K^{-1}$の第1行を作るには、まず第1列を取り除く。

$K=\begin{bmatrix}c_1+c_2&-c_2&0\\ -c_2&c_2+c_3&-c_3\\ 0&-c_3&c_3+c_4\end{bmatrix}\:\longrightarrow\:
\begin{bmatrix}-c_2&0\\c_2+c_3&-c_3\\-c_3&c_3+c_4\end{bmatrix}$  

そしてこの3×2行列から各列を1つずつ消し、符号${(-1)}^{i+j}$を加えることで、余因子が 

$\begin{bmatrix}c_2+c_3&-c_3\\-c_3&c_3+c_4\end{bmatrix},\:
-\begin{bmatrix}-c_2&0\\-c_3&c_3+c_4\end{bmatrix},\:
\begin{bmatrix}-c_2&0\\c_2+c_3&-c_3\end{bmatrix}$  

と得られる。これらの行列式を計算することで、$K^{-1}$の第1行の成分の分子は

$\begin{bmatrix}c_2c_3+c_2c_4+c_3c_4&c_2c_3+c_2c_4&c_2c_3\end{bmatrix}$

と求められる。同様の処理を第2・3行に対しても行い、$K^{-1}$を求めよ。

### 解答
基本的には上記の通り手計算で頑張るだけ。

・第2行  
$\begin{bmatrix}c_1+c_2&-c_2&0\\ -c_2&c_2+c_3&-c_3\\ 0&-c_3&c_3+c_4\end{bmatrix}\:\longrightarrow\:
\begin{bmatrix}c_1+c_2&0\\ -c_2&-c_3\\ 0&c_3+c_4\end{bmatrix}\\ \:\longrightarrow\:
\begin{bmatrix}-c_2&-c_3\\ 0&c_3+c_4\end{bmatrix},\:
-\begin{bmatrix}c_1+c_2&0\\ 0&c_3+c_4\end{bmatrix},\:
\begin{bmatrix}c_1+c_2&0\\-c_2&-c_3\end{bmatrix}\\
\:\longrightarrow\:
\begin{bmatrix}c_2c_3+c_2c_4&c_1c_3+c_1c_4+c_2c_3+c_2c_4&c_1c_3+c_2c_3\end{bmatrix}$ 

・第3行  
$\begin{bmatrix}c_1+c_2&-c_2&0\\ -c_2&c_2+c_3&-c_3\\ 0&-c_3&c_3+c_4\end{bmatrix}\:\longrightarrow\:
\begin{bmatrix}c_1+c_2&-c_2\\ -c_2&c_2+c_3\\ 0&-c_3\end{bmatrix}\\ \:\longrightarrow\:
\begin{bmatrix}-c_2&c_2+c_3\\ 0&-c_3\end{bmatrix},\:
-\begin{bmatrix}c_1+c_2&-c_2\\ 0&-c_3\end{bmatrix},\:
\begin{bmatrix}c_1+c_2&-c_2\\ -c_2&c_2+c_3\end{bmatrix}\\
\:\longrightarrow\:
\begin{bmatrix}c_2c_3&c_1c_3+c_2c_3&c_1c_2+c_1c_3+c_2c_3\end{bmatrix}$ 

以上をまとめると、

$K^{-1}=\frac{1}{det\:K}\begin{bmatrix}c_2c_3+c_2c_4+c_3c_4&c_2c_3+c_2c_4&c_2c_3\\
c_2c_3+c_2c_4&c_1c_3+c_1c_4+c_2c_3+c_2c_4&c_1c_3+c_2c_3\\
c_2c_3&c_1c_3+c_2c_3&c_1c_2+c_1c_3+c_2c_3\end{bmatrix}$

となり、特に $c_i=1$ $(for\:\forall\:i)$ の場合は、

$K^{-1}=\frac{1}{4}\begin{bmatrix}
3&2&1\\2&4&2\\1&2&3\end{bmatrix}$  
<hr>

<hr>
## 2.1.3
半固定の式で$A^{-1}C^{-1}(A^T)^{-1}$を作ることで$(A^TCA)^{-1}$を求めよ。  
特に $c_i=1$ $(for\:\forall\:i)\leftrightarrow C=I$ で結果を確認せよ。

### 解答
半固定ではどれも正方行列のため、各行列の逆行列を作ることができる。  

$A^TCA=\begin{bmatrix}1&-1&0\\0&1&-1\\0&0&1\end{bmatrix}
\begin{bmatrix}c_1&&\\&c_2&\\&&c_3\end{bmatrix}
\begin{bmatrix}1&0&0\\-1&1&0\\0&-1&1\end{bmatrix}$  

これらの行列の逆行列を計算すると  

$(A^T)^{-1}=\begin{bmatrix}1&1&0\\0&1&1\\0&0&1\end{bmatrix}$, 
$A^{-1}=\begin{bmatrix}1&0&0\\1&1&0\\1&1&0\end{bmatrix}$, 
$C^{-1}=\frac{1}{c_1c_2c_3}\begin{bmatrix}c_2c_3&&\\&c_1c_3&\\&&c_1c_2\end{bmatrix}$  

以上を用いて計算すると  

$(A^TCA)^{-1}=\frac{1}{c_1c_2c_3} \begin{bmatrix}c_2c_3&c_2c_3&c_2c_3\\
c_2c_3&c_2c_3&c_2c_3+c_1c_3\\
c_2c_3&c_2c_3+c_1c_3&c_2c_3+c_1c_3+c_1c_2\end{bmatrix}$  

特に $c_i=1$ $(for\:\forall\:i)$ のときは、  

$(A^TCA)^{-1}=\begin{bmatrix}1&1&1\\1&2&2\\1&2&3\end{bmatrix}$……P105と一致
<hr>

<hr>
## 2.1.4
両端とも固定しない（無固定）と式(11)のように $A^TCA$ は非正則となるが、このとき $A^TCAu=f$ から得られる3つの方程式を加えることで、$f_1+f_2+f_3=0$ が必要になることを示せ。  
さらに、力が $f=(-1,\:0,\:1)$ と自身で釣り合っているときの上式の解と、すべての解を求めよ。

### 解答
無固定の剛体行列は、$K=\begin{bmatrix}c_2&-c_2&0\\-c_2&c_2+c_3&-c_3\\0&-c_3&c_3\end{bmatrix}$ という形。  

さらに前提として $u=(u_1,\:u_2,\:u_3)^T,\quad f=(f_1,\:f_2,\:f_3)^T$ とおいて $A^TCAu=f$ を解くと

$\left\{ \begin{array}{lll}
f_1=&c_2u_1&-c_2u_2&\\f_2=&-c_2u_1&+(c_2+c_3)u_2&-c_3u_3\\f_3=&&-c_3u_2&+c_3u_3\end{array}\right.$  

これらの式を足し合わせると、明らかに $f_1+f_2+f_3=0$ となっている。

特に $f=(f_1,\:f_2,\:f_3)^T=(-1,\:0,\:1)^T$ のときを計算すると、

$u_2=u_1+\frac{1}{c_2},\quad u_3=u_1+\frac{1}{c_2}+\frac{1}{c_3} \quad \longrightarrow \quad
u=u_1(1,\:1+\frac{1}{c_2u_1},\:1+\frac{1}{c_2u_1}+\frac{1}{c_3u_1})^T$

一般の $f$ のときは、例えば $f_1$ と $f_3$ を決めて $f_2$ を消去すると

$u_2=u_1-\frac{f_1}{c_2},\quad u_3=u_1-\frac{f_1}{c_2}-\frac{f_3}{c_3} \quad \longrightarrow \quad
u=u_1(1,\:1-\frac{f_1}{c_2u_1},\:1-\frac{f_1}{c_2u_1}-\frac{f_3}{c_3u_1})^T$
<hr>

<hr>
## 2.1.5
両固定の場合、上端のばね1と下端のばね4の（壁からの外部）反力は何か？  
(この力は、3つの質点を引き下ろそうとする重力の $3mg$ と釣り合うはずである)

### 解答
P104のように伸長が $\frac{mg}{c}(1.5,\:0.5,\:-0.5,\:-1.5)^T$ なので、ばね1とばね4の内力は $w_1=\frac{3}{2}mg,\:w_4=-\frac{3}{2}mg$ となる。  
※この $w$ の正負は、（伸長の正負を考慮すると）<u>ばねが縮むときに正</u>であって、
    $u$ のように<u>下向き正ではない</u>。

・ばね1を上の壁が支える外力は、( $w_1>0$ なので縮むのとは逆向きの) <u>上向き</u>に $\frac{3}{2}mg$  
・ばね4を下の壁が支える外力は、( $w_1<0$ なので伸びるのとは逆向きの) <u>上向き</u>に $\frac{3}{2}mg$  
……以上を合わせると全体で上向きに $3mg$ の力がかかっている。
<hr>

<hr>
## 2.1.6
半固定かつ $c_1=c_3=1$ のもとで、ばね2を強くした状況を考える。 $c_2=10,\:100$ に対して $K=A^TCA$ を求めよ。さらに等しい質点 $f=(1,\:1,\:1)^T$ のときの $u=K^{-1}f$ を計算せよ。

### 解答
半固定の剛体行列は、$K=\begin{bmatrix}c_1+c_2&-c_2&0\\-c_2&c_2+c_3&-c_3\\0&-c_3&c_3\end{bmatrix}$ という形。上記 $c$ の具体値などを入れて解くと、

$\left\{ \begin{array}{lll}
c_2=1&\cdots&K=\begin{bmatrix}2&-1&0\\-1&2&-1\\0&-1&1\end{bmatrix},
&K^{-1}=\begin{bmatrix}1&1&1\\1&2&2\\1&2&3\end{bmatrix},
&u=\begin{bmatrix}3\\5\\6\end{bmatrix}\\
c_2=10&\cdots&K=\begin{bmatrix}11&-10&0\\-10&11&-1\\0&-1&1\end{bmatrix},
&K^{-1}=\frac{1}{10}\begin{bmatrix}10&10&10\\10&11&11\\10&11&21\end{bmatrix},
=\begin{bmatrix}1&1&1\\1&1.1&1.1\\1&1.1&2.1\end{bmatrix}
&u=\begin{bmatrix}3\\3.2\\4.2\end{bmatrix}\\
c_2=100&\cdots&K=\begin{bmatrix}101&-100&0\\-100&101&-1\\0&-1&1\end{bmatrix},
&K^{-1}=\frac{1}{100}\begin{bmatrix}100&100&100\\100&101&101\\100&101&201\end{bmatrix},
=\begin{bmatrix}1&1&1\\1&1.01&1.01\\1&1.01&2.01\end{bmatrix}
&u=\begin{bmatrix}3\\3.02\\4.02\end{bmatrix}\\
\end{array}\right.$  

In [27]:
#2.1.6の計算:c2を変数にして
c2=10
f=np.array([1,1,1])
K=np.array([[1+c2,-c2,0],[-c2,c2+1,-1],[0,-1,1]])
print('K = ')
print(K)
invK=np.linalg.inv(K)
print('invK = ')
print(invK)
u=np.dot(invK,f)
print('u = ')
print(u)

K = 
[[ 11 -10   0]
 [-10  11  -1]
 [  0  -1   1]]
invK = 
[[ 1.   1.   1. ]
 [ 1.   1.1  1.1]
 [ 1.   1.1  2.1]]
u = 
[ 3.   3.2  4.2]


### 2.1.6　解答続き：上記結果の解釈
2つ目のばねの強さに関わらず、1つ目/3つ目のばねは（下にある3つ/1つの質点を支えるために）同じように伸びている。  
2つ目のばねが強くなるとほとんど伸びないため、1つ目と2つ目の質点の変位の差（＝2つ目のばねの伸び）はかなり小さくなる。  

もしも $c_2\rightarrow\infty$ となると、<u>1つ目の質点・2つ目のばね・2つ目の質点がまとめて1つの質点（重さ2）と近似</u>できる。  
この近似した状態を、質点2つの半固定から計算すると、

$K=\begin{bmatrix}c_1+c_2&-c_2\\-c_2&c_2\end{bmatrix}
=\begin{bmatrix}2&-1\\-1&1\end{bmatrix}\quad \longrightarrow \quad
K^{-1}=\begin{bmatrix}1&1\\1&2\end{bmatrix}\quad \longrightarrow \quad
u=K^{-1}f=\begin{bmatrix}1&1\\1&2\end{bmatrix}\begin{bmatrix}2\\1\end{bmatrix}
=\begin{bmatrix}3\\4\end{bmatrix}$

これは、上記プログラムの $c_2\rightarrow\infty$ 極限で得られた値の $[u_1(\simeq u_2),\:u_3]^T$ に対応する。
<hr>

<hr>
## 2.1.7
両固定かつ $c_1=c_3=c_4=1$ のもとで、$c_2\rightarrow0$ とばね2を弱くしたと考える。このとき、$K=A^TCA$ は可逆なままであり続けるだろうか？  
さらに、$Ku=f=(1,\:1,\:1)$ を解き、その解を物理的に説明せよ。

In [36]:
#2.1.7の計算:c2を変数にして
c2=1
print('c2 = ')
print(c2)
f=np.array([1,1,1])
K=np.array([[1+c2,-c2,0],[-c2,c2+1,-1],[0,-1,2]])
print('K = ')
print(K)
invK=np.linalg.inv(K)
print('invK = ')
print(invK)
u=np.dot(invK,f)
print('u = ')
print(u)

c2 = 
1
K = 
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
invK = 
[[ 0.75  0.5   0.25]
 [ 0.5   1.    0.5 ]
 [ 0.25  0.5   0.75]]
u = 
[ 1.5  2.   1.5]


### 2.1.7 解答
可逆性について：2.1.1において、両固定の行列式は$c_1c_2c_3+c_1c_3c_4+c_1c_2c_4+c_2c_3c_4$ なので、$c_2=0$ になっただけでは $det\:K=c_1c_3c_4$ となり0にはならないので可逆性は保たれる。

上記プログラムのように、$c_2\rightarrow0$ の極限では $u=[1,\:3,\:2]^T$ となる。  
この極限では2つ目のばねは機能しておらず、繋がっていないも同然であることを考えると、この極限の状態は<u>1つのばねの（上）半固定 + 2つのばねの（下）半固定</u>と近似できるはずである。

1つのばねの上半固定（天井から釣り下がった1つのばねと1つの質点）の変位が1なのは自明。  
2つのばねの下半固定（地面から伸びた2つのばねと2つの質点）について、このときの剛体行列から変位を求めると

$K=\begin{bmatrix}c_3&-c_3\\-c_3&c_3+c_4\end{bmatrix}
=\begin{bmatrix}1&-1\\-1&2\end{bmatrix}\quad \longrightarrow \quad
K^{-1}=\begin{bmatrix}2&1\\1&1\end{bmatrix}\quad \longrightarrow \quad
u=K^{-1}f=\begin{bmatrix}2&1\\1&1\end{bmatrix}\begin{bmatrix}1\\1\end{bmatrix}
=\begin{bmatrix}3\\2\end{bmatrix}$

これは確かに上記極限の $u=[u_2,\:u_3]^T$ と対応しており、上記近似が正しいことが確かめられた。
<hr>

<hr>
## 2.1.8
無固定の1つのばねに対して、$K$ を求めよ（これは区分行列の要素と考えると”要素行列”と呼べなくもない）。  
以下、3×3行列となる $K$ について、  
(a)ばね2と3に対する上記 $K$ を式(11)にあてはめ、無固定の $K_{free-free}$ を作れ。  
(b)次に、上端のばね1に対する $K$ を取り入れることで、半固定の $K_{fixed-free}$ を作れ。  
(c)さらに、下端のばね4に対する $K$ を取り入れることで、両固定の $K_{fixed-fixed}$ を作れ。

### 解答
無固定1ばね2質点： $e=Au,\quad w=Ce,\quad f=a^Tw$ の3方程式から求める

$e=(u_2-u_1)=(-1,\:1)\begin{pmatrix}u_1\\u_2\end{pmatrix},\quad
C=c,\quad f=\begin{pmatrix}-w\\w\end{pmatrix}=\begin{pmatrix}-1\\1\end{pmatrix}w\\
\quad \longrightarrow \quad
K=\begin{pmatrix}-1\\1\end{pmatrix}c\:(-1,\:1)=c\begin{pmatrix}1&-1\\-1&1\end{pmatrix}$

(a)　
$K_{free-free}=\begin{pmatrix}K_{c_2}&\begin{array}{ll}0\\0 \end{array}\\
\begin{array}{ll}0&0\end{array}&0\end{pmatrix}
+\begin{pmatrix}0&\begin{array}{ll}0&0\end{array}\\
\begin{array}{ll}0\\0 \end{array}&K_{c_3}\end{pmatrix}
=\begin{pmatrix}c_2&-c_2&\\-c_2&c_2+c_3&-c_3\\&-c_3&c_3\end{pmatrix}$

(b)上端は上半固定1ばね1質点なので、上記 $K$ において $u_1=f_1=0$ とおけばよく、
$K_{c_1}=\begin{pmatrix}0\\1\end{pmatrix}c_1\:(0,\:1)=\begin{pmatrix}0&0\\0&c_1\end{pmatrix}$  
配置場所に注意すると　
$K_{fixed-free}=\begin{pmatrix}c_1&\begin{array}{ll}0&0\end{array}\\\begin{array}{ll}0\\0\end{array}&0\end{pmatrix}+K_{free-free}=\begin{pmatrix}c_1+c_2&-c_2&\\-c_2&c_2+c_3&-c_3\\&-c_3&c_3\end{pmatrix}$

(c)下端は下半固定1ばね1質点なので、上記 $K$ において $u_2=f_2=0$ とおけばよく、
$K_{c_4}=\begin{pmatrix}1\\0\end{pmatrix}c_4\:(1,\:0)=\begin{pmatrix}c_4&0\\0&0\end{pmatrix}$  
配置場所に注意すると　
$K_{fixed-fixed}=\begin{pmatrix}0&\begin{array}{ll}0\\0\end{array}\\\begin{array}{ll}0&0\end{array}&c_4\end{pmatrix}+K_{fixed-free}=\begin{pmatrix}c_1+c_2&-c_2&\\-c_2&c_2+c_3&-c_3\\&-c_3&c_3+c_4\end{pmatrix}$
<hr>

<hr>
## 2.1.9
倒立振り子に対して $P'(\theta^{*})=0$ であるとき、$P''(\theta^{*})>0$ であって $\theta^{*}$ は安定であることを示せ。

### 解答
微分を手計算で頑張って解いていく（$0\leq\theta\leq\frac{\pi}{2}$）。

$P'(\theta^{*})=c\theta^{*}-mgLsin\theta^{*}=0\quad\longleftrightarrow\quad
mgL=\frac{c\theta^{*}}{sin\theta^{*}}$　より　
$P''(\theta^{*})=c-mgLcos\theta^{*}=c-\frac{c\theta^{*}cos\theta^{*}}{sin\theta^{*}}
=c(1-\frac{\theta^{*}}{tan\theta^{*}})$

ここで $g(\theta)=\frac{\theta cos\theta}{sin\theta}$ とおくと 
$g'(\theta)=\frac{sin2\theta-2\theta}{2sin^2\theta}$ であり、
さらに $h(\theta)=sin2\theta-2\theta$ とおくと 
$h'(\theta)=2cos2\theta-2\leq0$

よって $h(0)=0$ から $h(\theta)\leq0$ であるために $g'(\theta)\leq0$ が導かれ、
さらに $g(0)\rightarrow1-0$ であることから $g(\theta)\leq1$

これらから $P''(\theta)\geq0$ が示され、$\theta^{*}\neq0$ を合わせると $P''(\theta^{*})>0$

※この結果は、<u>直立以外で止まった状態なら必ず安定（微小外力がかかっても元に戻る）</u>ということを示している。  
逆に直立のときは必ず $P'(\theta)=0$ である一方で、微小外力によって $\theta\neq0$ となった場合は $c>mgL$ だとそのまま倒れてしまう。このことを図解したのが図2.3/4である。
<hr>

<hr>
## 2.1.10
剛性行列を $K=A^TCA=D-W$ のように、対角行列 $D$ と非対角行列 $W$ の差で表す（剛性行列の行和は0以上かつ $W\geq0$）。下の等式を証明することによって $K^{-1}$ の成分が正であることを示せ。

$KK^{-1}=(D-W)(D^{-1}+D^{-1}WD^{-1}+D^{-1}WD^{-1}WD^{-1}+\cdots)=I$

### 解答
上記無限級数が逆行列に収束して全ての項が非負であることを利用？
<hr>

<hr>
## 2.1.11
3個の質点が3つのばねにつながって上端が固定されている（上半固定3ばね3質点）。この状態でばね2を弱くして $c_2\rightarrow0$ となったとする。  
(a) $c_2=0$ のとき、$K$ はどのような特徴を持つか？　さらに $Ku=0$ の任意の解とすべての解を求め、これらの解を物理的に説明せよ。  
(b) $c_2=0$ のもとで、$Ku=f$ はどんな場合に解をもつか（これはなぜ物理的に合理的か）？  
(c) $c_2=0$ かつ $c_1=1,\:c_3=3$ のとき、$K$ の固有ベクトルは何か？

### 解答
上半固定なので $K=\begin{bmatrix}c_1+c_2&-c_2&0\\-c_2&c_2+c_3&-c_3\\0&-c_3&c_3\end{bmatrix}$ であり、この $c_2$ を0にすると $K=\begin{bmatrix}c_1&0&0\\0&c_3&-c_3\\0&-c_3&c_3\end{bmatrix}$

(a)このときの $K$ は一目でわかる通り特異な行列である。  
$u=(u_1,\:u_2,\:u_3)^T$ とおくと $Ku=0$ の方程式は $c_1u_1=c_3(u_2-u_3)=0$  
これを解くと $u_1=0,\:u_2=u_3$ となり $u=u_2(0,\:1,\:1)^T$

※解釈  
f=0なので外力は（重り含めて）かかっていない。  
重さがないので1つ目と3つ目のばねは当然伸びない（$e_1=u_1=0,\:e_3=u_3-u_2=0$）。  
しかし2つ目のばねはいくらでも伸びる（ある意味”空気”）ため $m_1$ ～ $m_2$ 間の距離（$=e_2$）は任意の値を取れる。  
この状態は（”空気”と考えれば）、<u>上半固定1ばね1質点と無固定1ばね2質点に分かれている</u>と言うこともできる。

(b) $Ku=f=(f_1,\:f_2,\:f_3)^T$ の方程式を書き下すと、 
$c_1u_1=f_1,\:c_3(u_2-u_3)=f_2,\:c_3(-u_2+u_3)=f_3$  
この式が成り立つためには、$f_2+f_3=0$ が必要となる。  
これは、無固定1ばね2質点の系で力のつり合いが保たれていることに対応する。

(c) $K=\begin{bmatrix}1&0&0\\0&3&-3\\0&-3&3\end{bmatrix}$ を解くと、　
$\lambda=0,\:1,\:6 \quad x=(0,\:-1,\:-1),\:(1,\:0,\:0),\:(0,\:-1,\:1)$

※解釈は？：図2.4右はうまく使えるかもしれない

<hr>