In [2]:
import numpy as np
import scipy.linalg as linalg
from matplotlib import pyplot
import scipy.sparse as sp
import scipy.sparse.linalg as spla
import math

<hr>
## 2.4.1
各グラフの接続行列 $A_{triangle},\, A_{square}$ とグラフラプラシアン行列 $A^{T}A$ を求めよ  
※誤植？：1→4を第3辺とする

### 解答
※各行列の作り方  
・接続行列：第 $x$ 辺がノード $a$ からノード $b$ へつながるとき、接続行列の第 $x$ 行の第 $a$ 列に $-1$ が、第 $b$ 列に $1$ が入る。  
・グラフラプラシアン行列：対角線上はそのノードに結ばれている変数、それ以外の $jk$要素は、ノード $j$ と $k$ の間が結ばれている場合に $-1$（結ばれないなら $0$）

$A_{tri}=\begin{bmatrix}-1&1&\\ &-1&1\\ -1&&1\end{bmatrix},\quad
A_{tri}^{T}A_{tri}=\begin{bmatrix} 2&-1&-1\\-1&2&-1\\-1&-1&2\end{bmatrix}$

$A_{squ}=\begin{bmatrix}-1&1&&\\ -1&&1&\\ -1&&&1\\ &-1&&1\\ &&-1&1\end{bmatrix},\quad
A_{squ}^{T}A_{squ}=\begin{bmatrix} 3&-1&-1&-1\\ -1&2&&-1\\-1&&2&-1\\ -1&-1&-1&3\end{bmatrix}$
<hr>

<hr>
## 2.4.2
$A_{tri},\,A_{tri}^{T}$ の零空間のすべてのベクトルを求めよ

### 解答
・$A_{tri}$  
$A_{tri}(u_1,\,u_2,\,u_3)^{T}=0$ より $u_1=u_2=u_3 \:\rightarrow\:u=c(1,1,1)^T$

・$A_{tri}^{T}$  
$A_{tri}^{T}\omega=0$ はKCL（キルヒホッフの電流則）なので式(7)に基づいて求める。  
$A_{tri}$ でのループフローは1種類（1→2→3→1）のため、解は1つで $\omega=c(1,1,-1)^T$

<hr>

<hr>
## 2.4.3
$A_{squ}u=0$ の解を1つ、$A_{squ}^T\omega=0$の解を2つ求めよ

### 解答
・$A_{squ}u=0$ …… 2.4.2と同様に解くことで、$u=c(1,1,1,1)^T$

・$A_{squ}^{T}\omega=0$  
今回の $A_{squ}$ のKCLで、ループフローは3種類ありそれぞれ求まる。  
1→3→4→1： $\omega=c(0,1,-1,0,1)^T$  
1→2→4→1： $\omega=c(1,0,-1,1,0)^T$  
1→2→4→3→1： $\omega=c(1,-1,0,1,-1)^T$

<hr>

<hr>
## 2.4.4
$n=100$ ノードの9×9の正方格子において、  
(a)辺の本数 $m$ 及び比率 $m/n$
(b)正方格子のそれぞれで、傾き1の対角線全てを辺に加えた時の $m$ と $m/n$

### 解答
(a) $m=9×10×2＝180$で、一般に1ノード4辺とつながるので $m/n=1.8\approx 2$  
(b) $1+2+\cdots+9+\cdots+1=81$ だけ辺が増えるので $m=261$であり、一般に1ノード6辺とつながるので $m/n=2.61\approx 3$

<hr>

<hr>
## 2.4.5
すべての連結グラフに対して、$Au=0$ の唯一の解が $u=c(1,\cdots,1)$ である理由を説明せよ

### 解答
一般に接続行列 $A$ は差分行列であり、各行には-1と1が1つずつ入る（各辺の接続の情報のため）。  
そのため、$A$ の各行と $u$ の積からは $-u_j+u_k＝0$ といった式が得られる。  
全ての行を連立することでどのノードについても上の関係式が成り立つため、すべての $u$ の要素は同じ値となる。

<hr>

<hr>
## 2.4.6
4ノードの完全グラフと木の $A^TA$ のトレースは12,6だが、このように $m$ 辺の任意のグラフに対してこの値が $2m$ となるのはなぜか？

### 解答
グラフラプラシアン行列の対角要素は、各ノードに結ばれている辺の数。  
$m$ 辺のとき、各辺が入力/出力で2回ずつ数えられるので、トレースが $2m$ になるのは当然。
<hr>

<hr>
## 2.4.7
4ノードの木で、その3個の辺がノード4に入っているとき、$K=A^{T}CA$ はどうなるか？  
ノードをアースして可逆になった $K$ と $det\,K$ を求めよ

### 解答
辺 $k$ がノード $k$ とノード4をつないでいると考える（$k=1,2,3$）。  
式(14)周辺を参考にすると、アースする前は
$K=\begin{bmatrix}c_1&&&-c_1\\&c_2&&-c_2\\&&c_3&-c_3\\-c_1&-c_2&-c_3&c_1+c_2+c_3\end{bmatrix}$  
ノード4をアースすることで第4列/行を削除して
$K=\begin{bmatrix}c_1&&\\&c_2&\\&&c_3\end{bmatrix},
\quad det\,K=c_1c_2c_3$  

<hr>

<hr>
## 2.4.8
完全グラフに対する6つの要素行列がどのように $K$ を組み立てるのか？  
※ノード $j$ と $k$ を結ぶ辺 $i$ に対する要素行列：
$K_i=\begin{bmatrix}c_i&-c_i\\-c_i&c_i\end{bmatrix}\begin{array}{}行j\\行k\end{array}$

### 解答
かなり自明だが、図2.19と対応させてかくならば、  
$K=\begin{bmatrix}c_1&-c_1&&\\-c_1&c_1&&\\&&&\\&&&\end{bmatrix}
+\begin{bmatrix}c_2&&-c_2&\\&&&\\-c_2&&c_2&\\&&&\end{bmatrix}
+\begin{bmatrix}&&&\\&-c_3&c_3&\\&c_3&-c_3&\\&&&\end{bmatrix}$
$\qquad+\begin{bmatrix}c_4&&&-c_4\\&&&\\&&&\\-c_4&&&c_4\end{bmatrix}
+\begin{bmatrix}&&&\\&c_5&&-c_5\\&&&\\&-c_5&&c_5\end{bmatrix}
+\begin{bmatrix}&&&\\&&&\\&&c_6&-c_6\\&&-c_6&c_6\end{bmatrix}$
$\quad=\begin{bmatrix}c_1+c_2+c_4&-c_1&-c_2&-c_4\\-c_1&c_1+c_3+c_5&-c_3&-c_5
\\-c_2&-c_3&c_2+c_3+c_6&-c_6\\-c_4&-c_5&-c_6&c_4+c_5+c_6\end{bmatrix}$  

<hr>

<hr>
## 2.4.9
5ノードが1列となった4辺の木において、追加演習2.5 Aを解いてみよ  
(1) $A^{T}A$　(2) アース済みの$K$　(3) $K^{-1}$　(4) $K$ の固有値　(5) $det\,K$

### 解答
辺 $k$ がノード $k$ と $k+1$ をつないでいるとする（$k=1\sim 4$）。  
(1) $A^{T}A=\begin{bmatrix}1&-1&&&\\-1&2&-1&&\\&-1&2&-1&\\&&-1&2&-1\\&&&-1&1\end{bmatrix}$　
(2) $K=\begin{bmatrix}1&-1&&\\-1&2&-1&\\&-1&2&-1\\&&-1&2\end{bmatrix}=T_4$  
(3) 1.1.1より $K^{-1}=T_4^{-1}=
\begin{bmatrix}4&3&2&1\\3&3&2&1\\2&2&2&1\\1&1&1&1\end{bmatrix}$


In [3]:
#2.4.9の続き
K=np.array([[1,-1,0,0],[-1,2,-1,0],[0,-1,2,-1],[0,0,-1,2]])
invK=np.linalg.inv(K)
la,v=np.linalg.eig(K)
print('K = ')
print(K)
print('固有値 = ')
print(la)
print('det K =')
print(np.linalg.det(K))

K = 
[[ 1 -1  0  0]
 [-1  2 -1  0]
 [ 0 -1  2 -1]
 [ 0  0 -1  2]]
固有値 = 
[ 0.12061476  3.53208889  2.34729636  1.        ]
det K =
1.0


<hr>

<hr>
## 2.4.10
1列に並んだ3つの抵抗器がコンダクタンス1,4,9を持つときの $K=A^{T}CA$ と $det\,K_{reduced}$ と固有値を求めよ

### 解答
第 $k$ 辺がコンダクタンス $k^2$ を持ち、ノード $k$ と $k+1$ をつなぐとする。  
式(14)に則ることで、
$K=\begin{bmatrix}1&-1&&\\-1&5&4&\\&-4&13&-9\\&&-9&9\end{bmatrix},\quad
K_{reduced}=\begin{bmatrix}1&-1&\\-1&5&4\\&-4&13\end{bmatrix}$

In [14]:
#2.4.10の続き
K=np.array([[1,-1,0],[-1,5,-4],[0,-4,13]])#ノード4をアース
#K=np.array([[5,-4,0],[-4,13,-9],[0,-9,9]])#ノード1をアース
invK=np.linalg.inv(K)
la,v=np.linalg.eig(K)
print('K = ')
print(K)
print('固有値 = ')
print(la)
print('det K =')
print(np.linalg.det(K))

K = 
[[ 1 -1  0]
 [-1  5 -4]
 [ 0 -4 13]]
固有値 = 
[  0.67019905   3.66217243  14.66762852]
det K =
36.0


<hr>
## 2.4.11
式(18)で、すべてのコンダクタンスが1かつ12Vのバッテリがあるときの $u,\omega$ を求めよ  
※編注：図2.19にあるような電流源はなく電圧源のみとする

### 解答
P151例1の電流源の話に則り、電圧源の場合を計算する。  
バッテリ目線だと、コンダクタンスについて $c_6→c_4$ と $c_3→c_1$ を通る2つの直列が並列につながり、その並列回路と $c_2$ が直列につながっている。  
$c_6→c_4$ と $c_3→c_1$ という各直列のコンダクタンスはそれぞれ $\frac{1}{2}$ であるので、それらをまとめた並列回路のコンダクタンスは1。  
その並列回路と $c_2$ を直列につないだ、全体のコンダクタンスは $\frac{1}{2}$ となる。  
よって、回路全体（＝ $c_2$）に流れる電流は $12×\frac{1}{2}=6[A]$  
この電流を2つの並列回路に等分配することで、$u=[-3,0,3,0],\,\omega=[-3,6,-3,-3,0,3]$

In [50]:
#2.4.11や例1を直接解いてみる
Cs=np.array([1,1,1,1,1,1])#各コンダクタンス
Vs=np.array([0,12,0,0,0,0])#電圧源
Is=np.array([-4,4,0])#電流源
A=np.array([[-1,1,0],[-1,0,1],[0,-1,1],[-1,0,0],[0,-1,0],[0,0,-1]])#接続行列

K=np.zeros((9,9))
K[0:6,6:9]=A
K[6:9,0:6]=A.T
K[0:6,0:6]=np.diag(1/Cs)
print('K = ')
print(K)

v=(np.hstack((Vs,Is))).T
print('v = ')
print(v)

wu=np.dot(np.linalg.inv(K),v)
print('w = ')
print(wu[0:6])
print('u = ')
print(wu[6:9])

K = 
[[ 1.  0.  0.  0.  0.  0. -1.  1.  0.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.  1.]
 [ 0.  0.  1.  0.  0.  0.  0. -1.  1.]
 [ 0.  0.  0.  1.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0. -1.]
 [-1. -1.  0. -1.  0.  0.  0.  0.  0.]
 [ 1.  0. -1.  0. -1.  0.  0.  0.  0.]
 [ 0.  1.  1.  0.  0. -1.  0.  0.  0.]]
v = 
[ 0 12  0  0  0  0 -4  4  0]
w = 
[-1.  7. -4. -2. -1.  3.]
u = 
[-2. -1.  3.]


<hr>
## 2.4.12
式(20)：追加演習2.5Aの $KK^{-1}=I$ を検算せよ。$K$ が正定値と分かるには？

### 解答
$KK^{-1}$の各要素について計算すると、  
対角要素：$\frac{2(n-1)-1×(n-2)}{n}=1$ 、　非対角要素：$\frac{(n-1)-2-1×(n-3)}{n}=0$  
となるので、計算結果は単位行列になる。

☆正定値と分かるためには？  
P70に正定値を示すための条件が羅列されている。  
例えば固有値が全て正ならばよいが、この $K$ の固有値は $1,n,\cdots,n$ なので満たす。
<hr>

<hr>
## 2.4.13
2.4.1の2つのグラフのすべての全域木を定めよ

### 解答
P153にある通り、その木がすべてのノードに到達していることが定義であり、その個数は $K$ の行列式。  
各行列式は3,8であり、それだけの個数の全域木があることとなる。以下に辺番号で解を記す。  
三角形：12,13,23、四角形：123,124,125,135,145,234,245,345
<hr>

<hr>
## 2.4.14
隣接行列（$A^TA=D-W$ の 非対角成分である $W$）の各要素は、ノード同士が辺で結ばれていれば-1でそうでなければ0となるが、それはどのようにして生み出されるか？

### 解答
接続行列 $A$ はm辺nノードならばm行n列である。  
そのi行j列要素は辺iとノードjの関係によって（出力：-1、入力：1、接続なし：0）と求まる。    
ラプラシアン行列 $A^TA$ のs行t列要素（以下(s,t)）は、  
　$A^T$ のs行と $A$ のt列を掛け合わせた結果  
　＝ $A$ のs列とt列のかけ合わせた結果  
　＝ノードsとノードtの入出力関係を掛け合わせた結果  
となっている。    
もしも辺kで2つのノードが繋がっているのならば、(s,k)と(t,k)に-1と1が含まれており、掛け合わせると-1が生まれる。その他の(s,:)と(t,:)の積は、いずれかが少なくとも0となるので、ラプラシアン行列の(s,t)は-1となる。  
もしも2つのノードが繋がっていないならば、上記後半の議論から(s,t)は0となる。
<hr>

<hr>
## 2.4.15
onesでは $\lambda=n-1,0,\cdots,0$ であることを既知として、追加演習2.5Aの $K^{-1}$ の固有値を求め、$K$ の固有値と比較せよ

### 解答
$K=\begin{bmatrix}n-1&-1&\cdots&-1\\-1&n-1&\cdots&-1\\ \vdots&\vdots&\ddots&\vdots\\-1&-1&\cdots&n-1\end{bmatrix},\quad
\lambda_K=1,n,\cdots,n,\quad
K^{-1}=\frac{1}{n}\begin{bmatrix}2&1&\cdots&1\\1&2&\cdots&1\\ \vdots&\vdots&\ddots&\vdots\\1&1&\cdots&2\end{bmatrix}$  
$K^{-1}=\frac{1}{n}(I+E)$ の固有値は、$\lambda_I=1,1,\cdots,1,\,\lambda_E=n-1,0,\cdots,0$ を用いることで、$\lambda_{K^{-1}}=1,\frac{1}{n},\cdots,\frac{1}{n}$ と求まる
（一般に $\lambda_{K^{-1}}=\frac{1}{\lambda_K}$ であることと一致）。
<hr>

<hr>
## 2.4.16
6辺4ノードの完全グラフ（図2.16）の全域木を書き下せ

### 解答
辺番号を使って書き下す。  
124,125,126,134,135,136,146,156  
234,235,236,245,256  
345,346  
456
<hr>

<hr>
## 2.4.17
3×3の正方格子は12辺9ノード。9×9のラプラシアン行列の要素を2数字を並べて書く。  
(a) $A^TA$ の81個の成分のうちゼロはいくつか？  
(b) ラプラシアン行列の主対角D(次数行列)を書き下せ  
(c) -Wにおいて、なぜ $d_{55}=4$ かつ $d_{52}=d_{54}=d_{56}=d_{58}=-1$ なのか？

### 解答
(a)対角の9要素と、辺の入出力に対応する12×2＝24要素が0以外なので、ゼロは48個。  
(b)対角要素は各ノードにつながる辺の数：(2,3,2,3,4,3,2,3,2)  
(c)ノード5が、ノード3/4/6/7の計4つとつながっているため。  
　※1次元の2階差分が(-1,2,1)を作ることの2次元版
<hr>

<hr>
## 2.4.18~22
正方格子についていくつか計算を行うことで色々なレジスタンスを計算する。  

### 2.4.18
N=3のもとで、(1,1)から(3,3)へ電流1を送り、(3,3)をアース。  
→電圧u(1,1)=-1.5 …… 両隅間の格子レジスタンス

### 2.4.19
N=4のもとで、(2,2)から(3,3)へ電流1を送り、(2,2)をアース。  
→電圧u(3,3)=0.71428571=5/7 …… 隣接対角間の格子レジスタンス

### 2.4.20
N=10のもとで、(5,5)/(6,6)周辺で問題19を繰り返す（アース(5,5)）。  
→電圧u(6,6)=0.64776162=217/335 …… 隣接対角間の格子レジスタンス  
※N=50のとき0.63705777、2/$\pi$=0.6366

### 2.4.21
N=10のもとで、(5,6)から(5,5)へ電流1を送り、(5,6)をアース。  
→電圧u(5,5)=0.50568843=1289/2549 …… 隣接間の格子レジスタンス

### 2.4.22
N=$\infty$のもとで、最近接ノード間のレジスタンスは？  
……問題21のNを大きくし、中央付近でアース/電流。  
→N=50のとき電圧u(25,25)=0.50021918$\approx$0.5  
※なぜなのか？
<hr>

In [3]:
#2.4.18～22までの説明をするためのスクリプト
n=50#正方格子の一辺

#ラプラシアン行列の作成
b=np.zeros((1,n))
b[0,0]=2
b[0,1]=-1
B=linalg.toeplitz(b)
B[0,0]=1
B[n-1,n-1]=1
#print('B = ')
#print(B)
L=np.kron(B,np.eye(n))+np.kron(np.eye(n),B)
#print('ラプラシアン行列：L = ')
#print(L)

#1つのノードをアース：ラプラシアン行列の変化
gp=np.array([25,26])#アースの座標
gnum=(gp[0]-1)*n+gp[1]#ノード番号を計算
#gnum=9#ノード番号の直接入力
K=np.delete(np.delete(L,gnum-1,0),gnum-1,1)
#print('アース済みのラプラシアン行列：K = ')
#print(K)

#電流ベクトルfを作成
fi=np.array([25,26])#入力の座標
finum=(fi[0]-1)*n+fi[1]#入力のノード番号
#finum=1#入力のノード番号の直接入力
fo=np.array([25,25])#出力の座標
fonum=(fo[0]-1)*n+fo[1]#入力のノード番号
#fonum=1#出力のノード番号の直接入力
f0=np.zeros((n*n,1))#アース前の電流ベクトル
f0[finum-1,0]=-1#入力
f0[fonum-1,0]=1#出力
f=np.delete(f0,gnum-1,0)#アースをして一部削除
#print('電流ベクトル：transpose(f) = ')
#print(f.T)

#Ku=fを逆行列から解く
u=np.dot(np.linalg.inv(K),f)
#print('電圧ベクトル：transpose(u) = ')
#print(u.T)
up=np.array([25,25])#知りたい電圧の位置
unum0=(up[0]-1)*n+up[1]
unum=unum0 if unum0<gnum else unum0-1 
print('電圧：u = ')
print(u[unum-1])

電圧：u = 
[ 0.50021918]
